# Generated by Django 6.0.3 on 2026-03-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_split_import_export_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='measurement_system',
            field=models.CharField(choices=[('auto', 'Auto'), ('metric', 'Metric'), ('imperial', 'Imperial')], default='auto', max_length=10, verbose_name='Measurement System'),
        ),
    ]
