# Generated by Django 6.0.3 on 2026-03-22 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_measurement_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_provide_port_corrections',
            field=models.BooleanField(default=False, help_text='Allows users to suggest corrections for misclassified ports (triggering retraining)', verbose_name='Can provide port corrections'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_provide_port_training',
            field=models.BooleanField(default=False, help_text='Allows users to submit labeled port images for YOLO model training', verbose_name='Can provide port training data (annotations)'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_model_training_status',
            field=models.BooleanField(default=False, help_text='Allows users to monitor YOLO training progress and validation metrics', verbose_name='Can view model training status'),
        ),
        migrations.CreateModel(
            name='SecurityAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('port_annotate', 'Port annotation submitted'), ('port_correction', 'Port correction submitted'), ('model_retrain', 'Model retraining triggered'), ('model_update', 'Model weights updated'), ('logout', 'User logged out'), ('login_failed', 'Failed login attempt')], db_index=True, max_length=20, verbose_name='Action')),
                ('resource_type', models.CharField(blank=True, max_length=50, verbose_name='Resource Type (e.g. port, model)')),
                ('resource_id', models.CharField(blank=True, max_length=255, verbose_name='Resource ID (e.g. image filename)')),
                ('delta_data', models.JSONField(blank=True, default=dict, help_text='For corrections: {old_label, new_label, position}', verbose_name='Change data (JSON)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Client IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Security Audit Log',
                'verbose_name_plural': 'Security Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='accounts_se_user_id_f05e4d_idx'), models.Index(fields=['action', 'timestamp'], name='accounts_se_action_20b74d_idx')],
            },
        ),
    ]
