# Generated by Django 5.1.5 on 2025-02-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterlocation',
            name='operational_since',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
