# Generated by Django 5.1.5 on 2025-02-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0002_alter_datacenterlocation_operational_since'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterlocation',
            name='manager',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datacenterlocation',
            name='manager_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
