# Generated by Django 5.1.5 on 2025-02-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0003_datacenterlocation_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenterlocation',
            name='short_name',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datacenterlocation',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
