# Generated by Django 5.1.5 on 2025-02-02 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0004_datacenterlocation_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterlocation',
            name='short_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
