# Generated by Django 5.1.5 on 2025-02-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0005_alter_datacenterlocation_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterlocation',
            name='short_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
