# Generated by Django 5.1.5 on 2025-02-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0006_alter_datacenterlocation_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenterlocation',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
