# Generated by Django 5.1.5 on 2025-02-03 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0007_alter_datacenterlocation_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCenterLocationCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=255)),
                ('data_center_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='dc.datacenterlocation')),
            ],
        ),
    ]
