# Generated by Django 5.1.5 on 2025-02-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0008_datacenterlocationcustomfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datacenterlocationcustomfield',
            name='data_center_location',
        ),
        migrations.AddField(
            model_name='datacenterlocation',
            name='custom_fields',
            field=models.ManyToManyField(to='dc.datacenterlocationcustomfield'),
        ),
    ]
