# Generated by Django 5.1.5 on 2025-02-05 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0010_location_locationcustomfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custom_fields',
            field=models.ManyToManyField(blank=True, related_name='custom_field', to='dc.locationcustomfield'),
        ),
    ]
