# Generated by Django 5.1.5 on 2025-02-05 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dc', '0011_location_custom_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='custom_fields',
        ),
    ]
