export * from './asset.service';
import { AssetService } from './asset.service';
export * from './asset.serviceInterface';
export * from './datacenter.service';
import { DatacenterService } from './datacenter.service';
export * from './datacenter.serviceInterface';
export * from './location.service';
import { LocationService } from './location.service';
export * from './location.serviceInterface';
export const APIS = [AssetService, DatacenterService, LocationService];
