/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders } from '@angular/common/http';

import { Observable } from 'rxjs';

import {
  Asset,
  AssetAssetModelImportCreateRequest,
  AssetCustomField,
  AssetModel,
  AssetModelPort,
  AssetRequest,
  AssetRequestClarify,
  AssetRequestCreate,
  AssetRequestPlan,
  AssetRequestReject,
  AssetRequestResubmit,
  AssetState,
  AssetType,
  GenericComponent,
  PaginatedAssetCustomFieldList,
  PaginatedAssetList,
  PaginatedAssetModelList,
  PaginatedAssetModelPortList,
  PaginatedAssetRequestList,
  PaginatedAssetStateList,
  PaginatedAssetTypeList,
  PaginatedGenericComponentList,
  PaginatedRackUnitList,
  PaginatedVendorList,
  PatchedAsset,
  PatchedAssetCustomField,
  PatchedAssetModel,
  PatchedAssetModelPort,
  PatchedAssetState,
  PatchedAssetType,
  PatchedGenericComponent,
  PatchedRackUnit,
  PatchedVendor,
  PortAnalyzeRequest,
  PortAnalyzeResult,
  PortAnnotateRequest,
  PortAnnotateResponse,
  PortClickAnalyzeRequest,
  PortClickAnalyzeResponse,
  PortCorrectionRequest,
  PortCorrectionResponse,
  PrivateMediaSignedUrlRequest,
  PrivateMediaSignedUrlResponse,
  RackUnit,
  Vendor,
} from '../model/models';

import { Configuration } from '../configuration';

export interface AssetAssetBulkCloneCreateRequestParams {
  asset: Asset;
}

export interface AssetAssetBulkDeleteCreateRequestParams {
  asset: Asset;
}

export interface AssetAssetBulkStatePartialUpdateRequestParams {
  patchedAsset?: PatchedAsset;
}

export interface AssetAssetCloneCreateRequestParams {
  id: number;
  asset: Asset;
}

export interface AssetAssetCreateRequestParams {
  asset: Asset;
}

export interface AssetAssetCustomFieldCreateRequestParams {
  assetCustomField?: AssetCustomField;
}

export interface AssetAssetCustomFieldDestroyRequestParams {
  id: number;
}

export interface AssetAssetCustomFieldListRequestParams {
  asset?: number;
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
}

export interface AssetAssetCustomFieldPartialUpdateRequestParams {
  id: number;
  patchedAssetCustomField?: PatchedAssetCustomField;
}

export interface AssetAssetCustomFieldRetrieveRequestParams {
  id: number;
}

export interface AssetAssetCustomFieldUpdateRequestParams {
  id: number;
  assetCustomField?: AssetCustomField;
}

export interface AssetAssetDestroyRequestParams {
  id: number;
}

export interface AssetAssetHistoryRetrieveRequestParams {
  id: number;
}

export interface AssetAssetImportCsvCreateRequestParams {
  file: Blob;
}

export interface AssetAssetListRequestParams {
  hostname?: string;
  model?: number;
  modelType?: number;
  modelVendor?: number;
  notInRack?: boolean;
  orderId?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  sapId?: string;
  search?: string;
  serialNumber?: string;
  state?: number;
}

export interface AssetAssetModelBulkDeleteCreateRequestParams {
  assetModel: AssetModel;
}

export interface AssetAssetModelCreateRequestParams {
  assetModel: AssetModel;
}

export interface AssetAssetModelDestroyRequestParams {
  id: number;
}

export interface AssetAssetModelImportCreateRequestParams {
  assetAssetModelImportCreateRequest?: AssetAssetModelImportCreateRequest;
}

export interface AssetAssetModelListRequestParams {
  name?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
  type?: number;
  vendor?: number;
}

export interface AssetAssetModelPartialUpdateRequestParams {
  id: number;
  patchedAssetModel?: PatchedAssetModel;
}

export interface AssetAssetModelPortCreateRequestParams {
  assetModelPort: AssetModelPort;
}

export interface AssetAssetModelPortDestroyRequestParams {
  id: number;
}

export interface AssetAssetModelPortListRequestParams {
  assetModel?: number;
  ordering?: string;
  page?: number;
  pageSize?: number;
}

export interface AssetAssetModelPortPartialUpdateRequestParams {
  id: number;
  patchedAssetModelPort?: PatchedAssetModelPort;
}

export interface AssetAssetModelPortRetrieveRequestParams {
  id: number;
}

export interface AssetAssetModelPortUpdateRequestParams {
  id: number;
  assetModelPort: AssetModelPort;
}

export interface AssetAssetModelRetrieveRequestParams {
  id: number;
}

export interface AssetAssetModelUpdateRequestParams {
  id: number;
  assetModel: AssetModel;
}

export interface AssetAssetMoveCreateRequestParams {
  id: number;
  asset: Asset;
}

export interface AssetAssetPartialUpdateRequestParams {
  id: number;
  patchedAsset?: PatchedAsset;
}

export interface AssetAssetRequestClarifyCreateRequestParams {
  id: number;
  assetRequestClarify: AssetRequestClarify;
}

export interface AssetAssetRequestCreateRequestParams {
  assetRequestCreate: AssetRequestCreate;
}

export interface AssetAssetRequestExecuteCreateRequestParams {
  id: number;
  assetRequest: AssetRequest;
}

export interface AssetAssetRequestListRequestParams {
  asset?: number;
  assignedTo?: number;
  createdBy?: number;
  ordering?: string;
  page?: number;
  pageSize?: number;
  requestType?:
    | 'decommissioning'
    | 'maintenance'
    | 'registration'
    | 'relocation';
  search?: string;
  status?:
    | 'executed'
    | 'needs_clarification'
    | 'planned'
    | 'rejected'
    | 'submitted';
}

export interface AssetAssetRequestPlanCreateRequestParams {
  id: number;
  assetRequestPlan?: AssetRequestPlan;
}

export interface AssetAssetRequestRejectCreateRequestParams {
  id: number;
  assetRequestReject: AssetRequestReject;
}

export interface AssetAssetRequestResubmitCreateRequestParams {
  id: number;
  assetRequestResubmit?: AssetRequestResubmit;
}

export interface AssetAssetRequestRetrieveRequestParams {
  id: number;
}

export interface AssetAssetRetrieveRequestParams {
  id: number;
}

export interface AssetAssetStateCreateRequestParams {
  assetState: AssetState;
}

export interface AssetAssetStateDestroyRequestParams {
  id: number;
}

export interface AssetAssetStateListRequestParams {
  name?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
}

export interface AssetAssetStatePartialUpdateRequestParams {
  id: number;
  patchedAssetState?: PatchedAssetState;
}

export interface AssetAssetStateRetrieveRequestParams {
  id: number;
}

export interface AssetAssetStateUpdateRequestParams {
  id: number;
  assetState: AssetState;
}

export interface AssetAssetTypeCreateRequestParams {
  assetType: AssetType;
}

export interface AssetAssetTypeDestroyRequestParams {
  id: number;
}

export interface AssetAssetTypeListRequestParams {
  name?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
}

export interface AssetAssetTypePartialUpdateRequestParams {
  id: number;
  patchedAssetType?: PatchedAssetType;
}

export interface AssetAssetTypeRetrieveRequestParams {
  id: number;
}

export interface AssetAssetTypeUpdateRequestParams {
  id: number;
  assetType: AssetType;
}

export interface AssetAssetUpdateRequestParams {
  id: number;
  asset: Asset;
}

export interface AssetGenericComponentCreateRequestParams {
  genericComponent: GenericComponent;
}

export interface AssetGenericComponentDestroyRequestParams {
  id: number;
}

export interface AssetGenericComponentListRequestParams {
  componentType?:
    | 'blanking_panel'
    | 'cable_manager'
    | 'other'
    | 'patch_panel'
    | 'pdu'
    | 'shelf';
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
}

export interface AssetGenericComponentPartialUpdateRequestParams {
  id: number;
  patchedGenericComponent?: PatchedGenericComponent;
}

export interface AssetGenericComponentRetrieveRequestParams {
  id: number;
}

export interface AssetGenericComponentUpdateRequestParams {
  id: number;
  genericComponent: GenericComponent;
}

export interface AssetPortAnalyzeCreateRequestParams {
  portAnalyzeRequest: PortAnalyzeRequest;
}

export interface AssetPortAnnotateCreateRequestParams {
  portAnnotateRequest: PortAnnotateRequest;
}

export interface AssetPortClickAnalyzeCreateRequestParams {
  portClickAnalyzeRequest: PortClickAnalyzeRequest;
}

export interface AssetPortCorrectionCreateRequestParams {
  portCorrectionRequest: PortCorrectionRequest;
}

export interface AssetPrivateMediaUrlCreateRequestParams {
  privateMediaSignedUrlRequest: PrivateMediaSignedUrlRequest;
}

export interface AssetRackUnitCreateRequestParams {
  rackUnit: RackUnit;
}

export interface AssetRackUnitDestroyRequestParams {
  id: number;
}

export interface AssetRackUnitListRequestParams {
  deviceHostname?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  rackName?: string;
  rackRoom?: number;
  search?: string;
}

export interface AssetRackUnitPartialUpdateRequestParams {
  id: number;
  patchedRackUnit?: PatchedRackUnit;
}

export interface AssetRackUnitRetrieveRequestParams {
  id: number;
}

export interface AssetRackUnitReturnToStockCreateRequestParams {
  id: number;
  rackUnit: RackUnit;
}

export interface AssetRackUnitUpdateRequestParams {
  id: number;
  rackUnit: RackUnit;
}

export interface AssetVendorCreateRequestParams {
  vendor: Vendor;
}

export interface AssetVendorDestroyRequestParams {
  id: number;
}

export interface AssetVendorListRequestParams {
  name?: string;
  ordering?: string;
  page?: number;
  pageSize?: number;
  search?: string;
}

export interface AssetVendorPartialUpdateRequestParams {
  id: number;
  patchedVendor?: PatchedVendor;
}

export interface AssetVendorRetrieveRequestParams {
  id: number;
}

export interface AssetVendorUpdateRequestParams {
  id: number;
  vendor: Vendor;
}

export interface AssetServiceInterface {
  defaultHeaders: HttpHeaders;
  configuration: Configuration;

  /**
   *
   * POST /asset/asset/bulk_clone Body: { \&quot;ids\&quot;: [1, 2, 3] } Clones each listed asset. Returns: { \&quot;created\&quot;: &lt;int&gt; }
   * @endpoint post /asset/asset/bulk_clone
   * @param requestParameters
   */
  assetAssetBulkCloneCreate(
    requestParameters: AssetAssetBulkCloneCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * POST /asset/asset/bulk_delete Body: { \&quot;ids\&quot;: [1, 2, 3] }   → delete those specific assets       {}  + filter params    → delete all assets matching current filters  Assets currently mounted in a rack are skipped. Returns: { \&quot;deleted\&quot;: &lt;int&gt;, \&quot;skipped\&quot;: &lt;int&gt; }
   * @endpoint post /asset/asset/bulk_delete
   * @param requestParameters
   */
  assetAssetBulkDeleteCreate(
    requestParameters: AssetAssetBulkDeleteCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * PATCH /asset/asset/bulk_state?search&#x3D;...&amp;state&#x3D;...&amp;model__type&#x3D;... Body: { \&quot;state_id\&quot;: &lt;int&gt; }  Updates the state of ALL assets matching the current filter params. Requires can_edit_assets. Forbidden for in_production (use move instead). Writes an AssetTransitionLog entry for each affected asset. Returns: { \&quot;updated\&quot;: &lt;int&gt; }
   * @endpoint patch /asset/asset/bulk_state
   * @param requestParameters
   */
  assetAssetBulkStatePartialUpdate(
    requestParameters: AssetAssetBulkStatePartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * POST /asset/asset/{id}/clone Creates a copy of the given asset (unique fields get CLONE-* placeholders). Returns the newly created asset.
   * @endpoint post /asset/asset/{id}/clone
   * @param requestParameters
   */
  assetAssetCloneCreate(
    requestParameters: AssetAssetCloneCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/asset
   * @param requestParameters
   */
  assetAssetCreate(
    requestParameters: AssetAssetCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint post /asset/asset_custom_field
   * @param requestParameters
   */
  assetAssetCustomFieldCreate(
    requestParameters: AssetAssetCustomFieldCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetCustomField>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint delete /asset/asset_custom_field/{id}
   * @param requestParameters
   */
  assetAssetCustomFieldDestroy(
    requestParameters: AssetAssetCustomFieldDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint get /asset/asset_custom_field
   * @param requestParameters
   */
  assetAssetCustomFieldList(
    requestParameters: AssetAssetCustomFieldListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetCustomFieldList>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint patch /asset/asset_custom_field/{id}
   * @param requestParameters
   */
  assetAssetCustomFieldPartialUpdate(
    requestParameters: AssetAssetCustomFieldPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetCustomField>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint get /asset/asset_custom_field/{id}
   * @param requestParameters
   */
  assetAssetCustomFieldRetrieve(
    requestParameters: AssetAssetCustomFieldRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetCustomField>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint put /asset/asset_custom_field/{id}
   * @param requestParameters
   */
  assetAssetCustomFieldUpdate(
    requestParameters: AssetAssetCustomFieldUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetCustomField>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint delete /asset/asset/{id}
   * @param requestParameters
   */
  assetAssetDestroy(
    requestParameters: AssetAssetDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   * Export assets as Excel (.xlsx)
   * GET /asset/export Accepts the same filters as AssetViewSet (search, state, model__type, ordering, ids). Returns an .xlsx file.
   * @endpoint get /asset/asset/export
   */
  assetAssetExportRetrieve(extraHttpRequestParams?: any): Observable<Blob>;

  /**
   *
   * GET /asset/asset/{id}/history Returns the ordered transition log for this asset (paginated).
   * @endpoint get /asset/asset/{id}/history
   * @param requestParameters
   */
  assetAssetHistoryRetrieve(
    requestParameters: AssetAssetHistoryRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   * Import assets from a CSV file
   * Process a CSV file and create Asset records.
   * @endpoint post /asset/asset/import-csv
   * @param requestParameters
   */
  assetAssetImportCsvCreate(
    requestParameters: AssetAssetImportCsvCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   * Download template CSV for asset import
   * Return a blank CSV template with the correct headers and one example row.
   * @endpoint get /asset/asset/import-csv
   */
  assetAssetImportCsvRetrieve(extraHttpRequestParams?: any): Observable<Blob>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset
   * @param requestParameters
   */
  assetAssetList(
    requestParameters: AssetAssetListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetList>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/asset_model/bulk_delete
   * @param requestParameters
   */
  assetAssetModelBulkDeleteCreate(
    requestParameters: AssetAssetModelBulkDeleteCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/asset_model
   * @param requestParameters
   */
  assetAssetModelCreate(
    requestParameters: AssetAssetModelCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint delete /asset/asset_model/{id}
   * @param requestParameters
   */
  assetAssetModelDestroy(
    requestParameters: AssetAssetModelDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   * Import an AssetModel from JSON (with optional base64 images)
   *
   * @endpoint post /asset/asset-model/import
   * @param requestParameters
   */
  assetAssetModelImportCreate(
    requestParameters: AssetAssetModelImportCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset_model
   * @param requestParameters
   */
  assetAssetModelList(
    requestParameters: AssetAssetModelListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetModelList>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint patch /asset/asset_model/{id}
   * @param requestParameters
   */
  assetAssetModelPartialUpdate(
    requestParameters: AssetAssetModelPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   *
   * @endpoint post /asset/asset_model_port
   * @param requestParameters
   */
  assetAssetModelPortCreate(
    requestParameters: AssetAssetModelPortCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModelPort>;

  /**
   *
   *
   * @endpoint delete /asset/asset_model_port/{id}
   * @param requestParameters
   */
  assetAssetModelPortDestroy(
    requestParameters: AssetAssetModelPortDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   *
   * @endpoint get /asset/asset_model_port
   * @param requestParameters
   */
  assetAssetModelPortList(
    requestParameters: AssetAssetModelPortListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetModelPortList>;

  /**
   *
   *
   * @endpoint patch /asset/asset_model_port/{id}
   * @param requestParameters
   */
  assetAssetModelPortPartialUpdate(
    requestParameters: AssetAssetModelPortPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModelPort>;

  /**
   *
   *
   * @endpoint get /asset/asset_model_port/{id}
   * @param requestParameters
   */
  assetAssetModelPortRetrieve(
    requestParameters: AssetAssetModelPortRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModelPort>;

  /**
   *
   *
   * @endpoint put /asset/asset_model_port/{id}
   * @param requestParameters
   */
  assetAssetModelPortUpdate(
    requestParameters: AssetAssetModelPortUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModelPort>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset_model/{id}
   * @param requestParameters
   */
  assetAssetModelRetrieve(
    requestParameters: AssetAssetModelRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint put /asset/asset_model/{id}
   * @param requestParameters
   */
  assetAssetModelUpdate(
    requestParameters: AssetAssetModelUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetModel>;

  /**
   *
   * POST /asset/asset/{id}/move Body: { \&quot;to_state\&quot;: &lt;int&gt;, \&quot;to_room\&quot;: &lt;int|null&gt;, \&quot;notes\&quot;: \&quot;\&quot; }  Records a state/location transition for the asset and updates it in place. Requires can_edit_assets. Enforces allowed transitions between standard states.
   * @endpoint post /asset/asset/{id}/move
   * @param requestParameters
   */
  assetAssetMoveCreate(
    requestParameters: AssetAssetMoveCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint patch /asset/asset/{id}
   * @param requestParameters
   */
  assetAssetPartialUpdate(
    requestParameters: AssetAssetPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * POST /asset/asset_request/{id}/clarify Body: { \&quot;clarification_notes\&quot;: \&quot;...\&quot; }  Transition → NEEDS_CLARIFICATION.
   * @endpoint post /asset/asset_request/{id}/clarify
   * @param requestParameters
   */
  assetAssetRequestClarifyCreate(
    requestParameters: AssetAssetRequestClarifyCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequestClarify>;

  /**
   *
   * Lifecycle management for asset requests.  Request lifecycle:     SUBMITTED → PLANNED → EXECUTED  (normal path)     SUBMITTED / PLANNED → REJECTED  (rejected)     SUBMITTED / PLANNED → NEEDS_CLARIFICATION → SUBMITTED  (clarification)  When a request is EXECUTED, the asset state and location are effectively updated and an AssetTransitionLog is created.
   * @endpoint post /asset/asset_request
   * @param requestParameters
   */
  assetAssetRequestCreate(
    requestParameters: AssetAssetRequestCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequestCreate>;

  /**
   *
   * POST /asset/asset_request/{id}/execute  Transition → EXECUTED. Applies the requested state/location transition on the asset, creates an AssetTransitionLog and marks the request as executed.
   * @endpoint post /asset/asset_request/{id}/execute
   * @param requestParameters
   */
  assetAssetRequestExecuteCreate(
    requestParameters: AssetAssetRequestExecuteCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequest>;

  /**
   *
   * Lifecycle management for asset requests.  Request lifecycle:     SUBMITTED → PLANNED → EXECUTED  (normal path)     SUBMITTED / PLANNED → REJECTED  (rejected)     SUBMITTED / PLANNED → NEEDS_CLARIFICATION → SUBMITTED  (clarification)  When a request is EXECUTED, the asset state and location are effectively updated and an AssetTransitionLog is created.
   * @endpoint get /asset/asset_request
   * @param requestParameters
   */
  assetAssetRequestList(
    requestParameters: AssetAssetRequestListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetRequestList>;

  /**
   *
   * POST /asset/asset_request/{id}/plan Body: { \&quot;planned_date\&quot;: \&quot;YYYY-MM-DD\&quot;, \&quot;assigned_to\&quot;: &lt;int|null&gt;, \&quot;notes\&quot;: \&quot;\&quot; }  Transition SUBMITTED → PLANNED.
   * @endpoint post /asset/asset_request/{id}/plan
   * @param requestParameters
   */
  assetAssetRequestPlanCreate(
    requestParameters: AssetAssetRequestPlanCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequestPlan>;

  /**
   *
   * POST /asset/asset_request/{id}/reject Body: { \&quot;rejection_notes\&quot;: \&quot;...\&quot; }  Transition → REJECTED (terminal).
   * @endpoint post /asset/asset_request/{id}/reject
   * @param requestParameters
   */
  assetAssetRequestRejectCreate(
    requestParameters: AssetAssetRequestRejectCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequestReject>;

  /**
   *
   * POST /asset/asset_request/{id}/resubmit Body: { \&quot;notes\&quot;: \&quot;...\&quot; }  (optional)  Transition NEEDS_CLARIFICATION → SUBMITTED. Only the original requester can resubmit their own request.
   * @endpoint post /asset/asset_request/{id}/resubmit
   * @param requestParameters
   */
  assetAssetRequestResubmitCreate(
    requestParameters: AssetAssetRequestResubmitCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequestResubmit>;

  /**
   *
   * Lifecycle management for asset requests.  Request lifecycle:     SUBMITTED → PLANNED → EXECUTED  (normal path)     SUBMITTED / PLANNED → REJECTED  (rejected)     SUBMITTED / PLANNED → NEEDS_CLARIFICATION → SUBMITTED  (clarification)  When a request is EXECUTED, the asset state and location are effectively updated and an AssetTransitionLog is created.
   * @endpoint get /asset/asset_request/{id}
   * @param requestParameters
   */
  assetAssetRequestRetrieve(
    requestParameters: AssetAssetRequestRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetRequest>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset/{id}
   * @param requestParameters
   */
  assetAssetRetrieve(
    requestParameters: AssetAssetRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint post /asset/asset_state
   * @param requestParameters
   */
  assetAssetStateCreate(
    requestParameters: AssetAssetStateCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetState>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint delete /asset/asset_state/{id}
   * @param requestParameters
   */
  assetAssetStateDestroy(
    requestParameters: AssetAssetStateDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint get /asset/asset_state
   * @param requestParameters
   */
  assetAssetStateList(
    requestParameters: AssetAssetStateListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetStateList>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint patch /asset/asset_state/{id}
   * @param requestParameters
   */
  assetAssetStatePartialUpdate(
    requestParameters: AssetAssetStatePartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetState>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint get /asset/asset_state/{id}
   * @param requestParameters
   */
  assetAssetStateRetrieve(
    requestParameters: AssetAssetStateRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetState>;

  /**
   *
   * ViewSet for CRUD operations on AssetState objects.
   * @endpoint put /asset/asset_state/{id}
   * @param requestParameters
   */
  assetAssetStateUpdate(
    requestParameters: AssetAssetStateUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetState>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/asset_type
   * @param requestParameters
   */
  assetAssetTypeCreate(
    requestParameters: AssetAssetTypeCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetType>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint delete /asset/asset_type/{id}
   * @param requestParameters
   */
  assetAssetTypeDestroy(
    requestParameters: AssetAssetTypeDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset_type
   * @param requestParameters
   */
  assetAssetTypeList(
    requestParameters: AssetAssetTypeListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedAssetTypeList>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint patch /asset/asset_type/{id}
   * @param requestParameters
   */
  assetAssetTypePartialUpdate(
    requestParameters: AssetAssetTypePartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetType>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/asset_type/{id}
   * @param requestParameters
   */
  assetAssetTypeRetrieve(
    requestParameters: AssetAssetTypeRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetType>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint put /asset/asset_type/{id}
   * @param requestParameters
   */
  assetAssetTypeUpdate(
    requestParameters: AssetAssetTypeUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<AssetType>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint put /asset/asset/{id}
   * @param requestParameters
   */
  assetAssetUpdate(
    requestParameters: AssetAssetUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Asset>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/generic_component
   * @param requestParameters
   */
  assetGenericComponentCreate(
    requestParameters: AssetGenericComponentCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<GenericComponent>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint delete /asset/generic_component/{id}
   * @param requestParameters
   */
  assetGenericComponentDestroy(
    requestParameters: AssetGenericComponentDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/generic_component
   * @param requestParameters
   */
  assetGenericComponentList(
    requestParameters: AssetGenericComponentListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedGenericComponentList>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint patch /asset/generic_component/{id}
   * @param requestParameters
   */
  assetGenericComponentPartialUpdate(
    requestParameters: AssetGenericComponentPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<GenericComponent>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/generic_component/{id}
   * @param requestParameters
   */
  assetGenericComponentRetrieve(
    requestParameters: AssetGenericComponentRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<GenericComponent>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint put /asset/generic_component/{id}
   * @param requestParameters
   */
  assetGenericComponentUpdate(
    requestParameters: AssetGenericComponentUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<GenericComponent>;

  /**
   *
   * POST /asset/port-analyze  Body: { \&quot;image_path\&quot;: \&quot;components/switch.jpg\&quot;, \&quot;side\&quot;: \&quot;front\&quot; }  Returns a list of detected ports: [{ \&quot;port_type\&quot;: \&quot;RJ45\&quot;, \&quot;pos_x\&quot;: 12.5, \&quot;pos_y\&quot;: 45.0,    \&quot;name\&quot;: \&quot;GigabitEthernet0/0\&quot;, \&quot;confidence\&quot;: 0.82 }, ...]  **Rate Limit**: 100 analyses per hour per user (prevents inference spam).
   * @endpoint post /asset/port-analyze
   * @param requestParameters
   */
  assetPortAnalyzeCreate(
    requestParameters: AssetPortAnalyzeCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Array<PortAnalyzeResult>>;

  /**
   *
   * POST /asset/port-annotate  Body: {     \&quot;image_path\&quot;: \&quot;components/switch.jpg\&quot;,     \&quot;side\&quot;: \&quot;front\&quot;,     \&quot;annotations\&quot;: [         { \&quot;port_type\&quot;: \&quot;RJ45\&quot;, \&quot;pos_x\&quot;: 12.5, \&quot;pos_y\&quot;: 45.0, \&quot;name\&quot;: \&quot;Gi0/0\&quot; }     ] }  Saves the annotations as YOLO training data. Il retraining è gestito esclusivamente da PortCorrectionView con logica smart.  **Permission**: Requires &#x60;can_provide_port_training&#x60; role permission. **Audit**: All submissions logged to SecurityAuditLog. **Rate Limit**: 10 annotations per hour per user (prevents training data poisoning).
   * @endpoint post /asset/port-annotate
   * @param requestParameters
   */
  assetPortAnnotateCreate(
    requestParameters: AssetPortAnnotateCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PortAnnotateResponse>;

  /**
   *
   * Single-click port detection endpoint.  **Rate Limit**: 200 clicks per hour per user (allows interactive exploration).
   * @endpoint post /asset/port-click-analyze
   * @param requestParameters
   */
  assetPortClickAnalyzeCreate(
    requestParameters: AssetPortClickAnalyzeCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PortClickAnalyzeResponse>;

  /**
   *
   * POST /asset/port-correction  Riceve una correzione manuale (predicted_type → actual_type) e: 1. Sovrascrive il sample di training con il tipo corretto. 2. Aggiorna il contatore di correzioni. 3. Lancia il retraining in background se le soglie sono raggiunte.  **Permission**: Requires &#x60;can_provide_port_corrections&#x60; role permission. **Audit**: All corrections logged to SecurityAuditLog. **Rate Limit**: 30 corrections per hour per user (prevents retraining floods).
   * @endpoint post /asset/port-correction
   * @param requestParameters
   */
  assetPortCorrectionCreate(
    requestParameters: AssetPortCorrectionCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PortCorrectionResponse>;

  /**
   *
   * POST /asset/private-media-url  Returns a short-lived signed URL for files under PRIVATE_MEDIA_SUBDIR.
   * @endpoint post /asset/private-media-url
   * @param requestParameters
   */
  assetPrivateMediaUrlCreate(
    requestParameters: AssetPrivateMediaUrlCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PrivateMediaSignedUrlResponse>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint post /asset/rack_unit
   * @param requestParameters
   */
  assetRackUnitCreate(
    requestParameters: AssetRackUnitCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<RackUnit>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint delete /asset/rack_unit/{id}
   * @param requestParameters
   */
  assetRackUnitDestroy(
    requestParameters: AssetRackUnitDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint get /asset/rack_unit
   * @param requestParameters
   */
  assetRackUnitList(
    requestParameters: AssetRackUnitListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedRackUnitList>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint patch /asset/rack_unit/{id}
   * @param requestParameters
   */
  assetRackUnitPartialUpdate(
    requestParameters: AssetRackUnitPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<RackUnit>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint get /asset/rack_unit/{id}
   * @param requestParameters
   */
  assetRackUnitRetrieve(
    requestParameters: AssetRackUnitRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<RackUnit>;

  /**
   *
   * Return installed component to warehouse: increment linked item quantity and remove component from rack.
   * @endpoint post /asset/rack_unit/{id}/return-to-stock
   * @param requestParameters
   */
  assetRackUnitReturnToStockCreate(
    requestParameters: AssetRackUnitReturnToStockCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<RackUnit>;

  /**
   *
   * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
   * @endpoint put /asset/rack_unit/{id}
   * @param requestParameters
   */
  assetRackUnitUpdate(
    requestParameters: AssetRackUnitUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<RackUnit>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint post /asset/vendor
   * @param requestParameters
   */
  assetVendorCreate(
    requestParameters: AssetVendorCreateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Vendor>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint delete /asset/vendor/{id}
   * @param requestParameters
   */
  assetVendorDestroy(
    requestParameters: AssetVendorDestroyRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<{}>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/vendor
   * @param requestParameters
   */
  assetVendorList(
    requestParameters: AssetVendorListRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<PaginatedVendorList>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint patch /asset/vendor/{id}
   * @param requestParameters
   */
  assetVendorPartialUpdate(
    requestParameters: AssetVendorPartialUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Vendor>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint get /asset/vendor/{id}
   * @param requestParameters
   */
  assetVendorRetrieve(
    requestParameters: AssetVendorRetrieveRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Vendor>;

  /**
   *
   * ViewSet mixin that writes a SecurityAuditLog entry after each successful create, update, or destroy operation.  Subclasses must set:     audit_resource_type  str  — e.g. \&#39;asset\&#39;, \&#39;vendor\&#39;, \&#39;rack\&#39;     audit_action_create  str  — SecurityAuditLog.Action value (or \&#39;\&#39; to skip)     audit_action_update  str     audit_action_delete  str
   * @endpoint put /asset/vendor/{id}
   * @param requestParameters
   */
  assetVendorUpdate(
    requestParameters: AssetVendorUpdateRequestParams,
    extraHttpRequestParams?: any,
  ): Observable<Vendor>;
}
