/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Asset } from '../model/models';
import { ListAssets200Response } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateAssetRequestParams {
    asset?: Asset;
}

export interface DestroyAssetRequestParams {
    id: string;
    ordering?: string;
    search?: string;
    hostname?: string;
    sapId?: string;
    serialNumber?: string;
    orderId?: string;
}

export interface ListAssetsRequestParams {
    page?: number;
    pageSize?: number;
    ordering?: string;
    search?: string;
    hostname?: string;
    sapId?: string;
    serialNumber?: string;
    orderId?: string;
}

export interface PartialUpdateAssetRequestParams {
    id: string;
    ordering?: string;
    search?: string;
    hostname?: string;
    sapId?: string;
    serialNumber?: string;
    orderId?: string;
    asset?: Asset;
}

export interface RetrieveAssetRequestParams {
    id: string;
    ordering?: string;
    search?: string;
    hostname?: string;
    sapId?: string;
    serialNumber?: string;
    orderId?: string;
}

export interface UpdateAssetRequestParams {
    id: string;
    ordering?: string;
    search?: string;
    hostname?: string;
    sapId?: string;
    serialNumber?: string;
    orderId?: string;
    asset?: Asset;
}


export interface AssetServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createAsset(requestParameters: CreateAssetRequestParams, extraHttpRequestParams?: any): Observable<Asset>;

    /**
     * 
     * 
* @param requestParameters
     */
    destroyAsset(requestParameters: DestroyAssetRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    listAssets(requestParameters: ListAssetsRequestParams, extraHttpRequestParams?: any): Observable<ListAssets200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    partialUpdateAsset(requestParameters: PartialUpdateAssetRequestParams, extraHttpRequestParams?: any): Observable<Asset>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrieveAsset(requestParameters: RetrieveAssetRequestParams, extraHttpRequestParams?: any): Observable<Asset>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateAsset(requestParameters: UpdateAssetRequestParams, extraHttpRequestParams?: any): Observable<Asset>;

}
