/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthDetail } from '../model/models';
import { ChangePassword } from '../model/models';
import { CookieTokenObtainRequest } from '../model/models';
import { LogoutRequest } from '../model/models';
import { MeResponse } from '../model/models';
import { PaginatedUserListList } from '../model/models';
import { PatchedUserPreferences } from '../model/models';
import { PatchedUserUpdate } from '../model/models';
import { Role } from '../model/models';
import { TokenObtainResponse } from '../model/models';
import { TokenRefreshRequest } from '../model/models';
import { TokenRefreshResponse } from '../model/models';
import { UserCreate } from '../model/models';
import { UserList } from '../model/models';
import { UserPreferences } from '../model/models';
import { UserUpdate } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AuthChangePasswordCreateRequestParams {
    changePassword: ChangePassword;
}

export interface AuthLogoutCreateRequestParams {
    logoutRequest: LogoutRequest;
}

export interface AuthPreferencesPartialUpdateRequestParams {
    patchedUserPreferences?: PatchedUserPreferences;
}

export interface AuthTokenBlacklistCreateRequestParams {
    logoutRequest: LogoutRequest;
}

export interface AuthTokenCreateRequestParams {
    cookieTokenObtainRequest: CookieTokenObtainRequest;
}

export interface AuthTokenRefreshCreateRequestParams {
    tokenRefreshRequest: TokenRefreshRequest;
}

export interface AuthUsersCreateRequestParams {
    userCreate: UserCreate;
}

export interface AuthUsersDestroyRequestParams {
    id: number;
}

export interface AuthUsersListRequestParams {
    limit?: number;
    offset?: number;
}

export interface AuthUsersPartialUpdateRequestParams {
    id: number;
    patchedUserUpdate?: PatchedUserUpdate;
}

export interface AuthUsersRetrieveRequestParams {
    id: number;
}

export interface AuthUsersUpdateRequestParams {
    id: number;
    userUpdate?: UserUpdate;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Allow any authenticated user to change their own password.
     * @endpoint post /auth/change-password/
* @param requestParameters
     */
    authChangePasswordCreate(requestParameters: AuthChangePasswordCreateRequestParams, extraHttpRequestParams?: any): Observable<ChangePassword>;

    /**
     * 
     * POST /auth/logout/  Invalidate the current refresh token (add to blacklist). Subsequent refresh attempts will fail, forcing re-authentication.
     * @endpoint post /auth/logout/
* @param requestParameters
     */
    authLogoutCreate(requestParameters: AuthLogoutCreateRequestParams, extraHttpRequestParams?: any): Observable<AuthDetail>;

    /**
     * 
     * Returns basic info, role permissions, and user preferences for the currently authenticated user.
     * @endpoint get /auth/me/
*/
    authMeRetrieve(extraHttpRequestParams?: any): Observable<MeResponse>;

    /**
     * 
     * GET / PATCH /auth/preferences/ — read or update the authenticated user\&#39;s preferences.
     * @endpoint patch /auth/preferences/
* @param requestParameters
     */
    authPreferencesPartialUpdate(requestParameters: AuthPreferencesPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<UserPreferences>;

    /**
     * 
     * GET / PATCH /auth/preferences/ — read or update the authenticated user\&#39;s preferences.
     * @endpoint get /auth/preferences/
*/
    authPreferencesRetrieve(extraHttpRequestParams?: any): Observable<UserPreferences>;

    /**
     * 
     * Read-only list of all available roles. Admin-only. Cached for 5 minutes.
     * @endpoint get /auth/roles/
*/
    authRolesList(extraHttpRequestParams?: any): Observable<Array<Role>>;

    /**
     * 
     * POST /auth/token/blacklist/  Read the refresh token from the cookie (or body), validate ownership, and add it to the JWT blacklist.  The cookie is always cleared, even if blacklisting fails, so the browser is left in a logged-out state regardless of server errors.
     * @endpoint post /auth/token/blacklist/
* @param requestParameters
     */
    authTokenBlacklistCreate(requestParameters: AuthTokenBlacklistCreateRequestParams, extraHttpRequestParams?: any): Observable<AuthDetail>;

    /**
     * 
     * POST /auth/token/  Accept &#x60;&#x60;username&#x60;&#x60; + &#x60;&#x60;password&#x60;&#x60; credentials.  On success:  - return &#x60;&#x60;access&#x60;&#x60; token and user &#x60;&#x60;role&#x60;&#x60; in the response body; - set an HTTP-only &#x60;&#x60;refresh_token&#x60;&#x60; cookie (never returned in body).  &#x60;&#x60;authentication_classes &#x3D; []&#x60;&#x60; prevents an expired *Bearer* header from triggering a premature 401 before credentials are even checked.
     * @endpoint post /auth/token/
* @param requestParameters
     */
    authTokenCreate(requestParameters: AuthTokenCreateRequestParams, extraHttpRequestParams?: any): Observable<TokenObtainResponse>;

    /**
     * 
     * POST /auth/token/refresh/  Read the refresh token from the HTTP-only cookie (falls back to the request body for transition compatibility).  Return a new &#x60;&#x60;access&#x60;&#x60; token plus the embedded &#x60;&#x60;role&#x60;&#x60; and &#x60;&#x60;username&#x60;&#x60; claims.  &#x60;&#x60;authentication_classes &#x3D; []&#x60;&#x60; prevents an expired *Bearer* header from triggering a 401 before the cookie is read. Respects &#x60;&#x60;ROTATE_REFRESH_TOKENS&#x60;&#x60; / &#x60;&#x60;BLACKLIST_AFTER_ROTATION&#x60;&#x60;.
     * @endpoint post /auth/token/refresh/
* @param requestParameters
     */
    authTokenRefreshCreate(requestParameters: AuthTokenRefreshCreateRequestParams, extraHttpRequestParams?: any): Observable<TokenRefreshResponse>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint post /auth/users/
* @param requestParameters
     */
    authUsersCreate(requestParameters: AuthUsersCreateRequestParams, extraHttpRequestParams?: any): Observable<UserCreate>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint delete /auth/users/{id}/
* @param requestParameters
     */
    authUsersDestroy(requestParameters: AuthUsersDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint get /auth/users/
* @param requestParameters
     */
    authUsersList(requestParameters: AuthUsersListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedUserListList>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint patch /auth/users/{id}/
* @param requestParameters
     */
    authUsersPartialUpdate(requestParameters: AuthUsersPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<UserUpdate>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint get /auth/users/{id}/
* @param requestParameters
     */
    authUsersRetrieve(requestParameters: AuthUsersRetrieveRequestParams, extraHttpRequestParams?: any): Observable<UserList>;

    /**
     * 
     * CRUD for User management. Accessible only by Admin role.
     * @endpoint put /auth/users/{id}/
* @param requestParameters
     */
    authUsersUpdate(requestParameters: AuthUsersUpdateRequestParams, extraHttpRequestParams?: any): Observable<UserUpdate>;

}
