/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AuthMeRetrieve200Response } from '../model/models';
import { TokenObtainPair } from '../model/models';
import { TokenRefresh } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface AuthTokenCreateRequestParams {
    tokenObtainPair: TokenObtainPair;
}

export interface AuthTokenRefreshCreateRequestParams {
    tokenRefresh: TokenRefresh;
}


export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Returns basic info about the currently authenticated user.
     * @endpoint get /auth/me/
*/
    authMeRetrieve(extraHttpRequestParams?: any): Observable<AuthMeRetrieve200Response>;

    /**
     * 
     * Takes a set of user credentials and returns an access and refresh JSON web token pair to prove the authentication of those credentials.
     * @endpoint post /auth/token/
* @param requestParameters
     */
    authTokenCreate(requestParameters: AuthTokenCreateRequestParams, extraHttpRequestParams?: any): Observable<TokenObtainPair>;

    /**
     * 
     * Takes a refresh type JSON web token and returns an access type JSON web token if the refresh token is valid.
     * @endpoint post /auth/token/refresh/
* @param requestParameters
     */
    authTokenRefreshCreate(requestParameters: AuthTokenRefreshCreateRequestParams, extraHttpRequestParams?: any): Observable<TokenRefresh>;

}
