/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ListLocationCustomFields200Response } from '../model/models';
import { ListLocations200Response } from '../model/models';
import { Location } from '../model/models';
import { LocationCustomField } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateLocationRequestParams {
    location?: Location;
}

export interface CreateLocationCustomFieldRequestParams {
    locationCustomField?: LocationCustomField;
}

export interface DestroyLocationRequestParams {
    id: string;
}

export interface DestroyLocationCustomFieldRequestParams {
    id: string;
}

export interface ListLocationCustomFieldsRequestParams {
    limit?: number;
    offset?: number;
}

export interface ListLocationsRequestParams {
    limit?: number;
    offset?: number;
}

export interface PartialUpdateLocationRequestParams {
    id: string;
    location?: Location;
}

export interface PartialUpdateLocationCustomFieldRequestParams {
    id: string;
    locationCustomField?: LocationCustomField;
}

export interface RetrieveLocationRequestParams {
    id: string;
}

export interface RetrieveLocationCustomFieldRequestParams {
    id: string;
}

export interface UpdateLocationRequestParams {
    id: string;
    location?: Location;
}

export interface UpdateLocationCustomFieldRequestParams {
    id: string;
    locationCustomField?: LocationCustomField;
}


export interface DatacenterServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createLocation(requestParameters: CreateLocationRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * 
* @param requestParameters
     */
    createLocationCustomField(requestParameters: CreateLocationCustomFieldRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * 
* @param requestParameters
     */
    destroyLocation(requestParameters: DestroyLocationRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    destroyLocationCustomField(requestParameters: DestroyLocationCustomFieldRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
* @param requestParameters
     */
    listLocationCustomFields(requestParameters: ListLocationCustomFieldsRequestParams, extraHttpRequestParams?: any): Observable<ListLocationCustomFields200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    listLocations(requestParameters: ListLocationsRequestParams, extraHttpRequestParams?: any): Observable<ListLocations200Response>;

    /**
     * 
     * 
* @param requestParameters
     */
    partialUpdateLocation(requestParameters: PartialUpdateLocationRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * 
* @param requestParameters
     */
    partialUpdateLocationCustomField(requestParameters: PartialUpdateLocationCustomFieldRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrieveLocation(requestParameters: RetrieveLocationRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * 
* @param requestParameters
     */
    retrieveLocationCustomField(requestParameters: RetrieveLocationCustomFieldRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateLocation(requestParameters: UpdateLocationRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * 
* @param requestParameters
     */
    updateLocationCustomField(requestParameters: UpdateLocationCustomFieldRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

}
