/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Location } from '../model/models';
import { LocationCustomField } from '../model/models';
import { PaginatedLocationCustomFieldList } from '../model/models';
import { PaginatedLocationList } from '../model/models';
import { PaginatedRoomList } from '../model/models';
import { PatchedLocation } from '../model/models';
import { PatchedLocationCustomField } from '../model/models';
import { PatchedRoom } from '../model/models';
import { Room } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface LocationLocationCreateRequestParams {
    location: Location;
}

export interface LocationLocationDestroyRequestParams {
    id: number;
}

export interface LocationLocationListRequestParams {
    name?: string;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
    shortName?: string;
}

export interface LocationLocationPartialUpdateRequestParams {
    id: number;
    patchedLocation?: PatchedLocation;
}

export interface LocationLocationRetrieveRequestParams {
    id: number;
}

export interface LocationLocationUpdateRequestParams {
    id: number;
    location: Location;
}

export interface LocationLocationcustomfieldCreateRequestParams {
    locationCustomField: LocationCustomField;
}

export interface LocationLocationcustomfieldDestroyRequestParams {
    id: number;
}

export interface LocationLocationcustomfieldListRequestParams {
    location?: number;
    ordering?: string;
    page?: number;
    pageSize?: number;
    search?: string;
}

export interface LocationLocationcustomfieldPartialUpdateRequestParams {
    id: number;
    patchedLocationCustomField?: PatchedLocationCustomField;
}

export interface LocationLocationcustomfieldRetrieveRequestParams {
    id: number;
}

export interface LocationLocationcustomfieldUpdateRequestParams {
    id: number;
    locationCustomField: LocationCustomField;
}

export interface LocationRoomCreateRequestParams {
    room: Room;
}

export interface LocationRoomDestroyRequestParams {
    id: number;
}

export interface LocationRoomListRequestParams {
    location?: number;
    ordering?: string;
    page?: number;
    pageSize?: number;
    roomType?: 'datacenter' | 'laboratory' | 'technical_office' | 'warehouse';
    search?: string;
}

export interface LocationRoomPartialUpdateRequestParams {
    id: number;
    patchedRoom?: PatchedRoom;
}

export interface LocationRoomRetrieveRequestParams {
    id: number;
}

export interface LocationRoomUpdateRequestParams {
    id: number;
    room: Room;
}


export interface LocationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint post /location/location
* @param requestParameters
     */
    locationLocationCreate(requestParameters: LocationLocationCreateRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint delete /location/location/{id}
* @param requestParameters
     */
    locationLocationDestroy(requestParameters: LocationLocationDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/location
* @param requestParameters
     */
    locationLocationList(requestParameters: LocationLocationListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedLocationList>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint patch /location/location/{id}
* @param requestParameters
     */
    locationLocationPartialUpdate(requestParameters: LocationLocationPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/location/{id}
* @param requestParameters
     */
    locationLocationRetrieve(requestParameters: LocationLocationRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint put /location/location/{id}
* @param requestParameters
     */
    locationLocationUpdate(requestParameters: LocationLocationUpdateRequestParams, extraHttpRequestParams?: any): Observable<Location>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint post /location/locationcustomfield
* @param requestParameters
     */
    locationLocationcustomfieldCreate(requestParameters: LocationLocationcustomfieldCreateRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint delete /location/locationcustomfield/{id}
* @param requestParameters
     */
    locationLocationcustomfieldDestroy(requestParameters: LocationLocationcustomfieldDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/locationcustomfield
* @param requestParameters
     */
    locationLocationcustomfieldList(requestParameters: LocationLocationcustomfieldListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedLocationCustomFieldList>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint patch /location/locationcustomfield/{id}
* @param requestParameters
     */
    locationLocationcustomfieldPartialUpdate(requestParameters: LocationLocationcustomfieldPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/locationcustomfield/{id}
* @param requestParameters
     */
    locationLocationcustomfieldRetrieve(requestParameters: LocationLocationcustomfieldRetrieveRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint put /location/locationcustomfield/{id}
* @param requestParameters
     */
    locationLocationcustomfieldUpdate(requestParameters: LocationLocationcustomfieldUpdateRequestParams, extraHttpRequestParams?: any): Observable<LocationCustomField>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint post /location/room
* @param requestParameters
     */
    locationRoomCreate(requestParameters: LocationRoomCreateRequestParams, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint delete /location/room/{id}
* @param requestParameters
     */
    locationRoomDestroy(requestParameters: LocationRoomDestroyRequestParams, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/room
* @param requestParameters
     */
    locationRoomList(requestParameters: LocationRoomListRequestParams, extraHttpRequestParams?: any): Observable<PaginatedRoomList>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint patch /location/room/{id}
* @param requestParameters
     */
    locationRoomPartialUpdate(requestParameters: LocationRoomPartialUpdateRequestParams, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint get /location/room/{id}
* @param requestParameters
     */
    locationRoomRetrieve(requestParameters: LocationRoomRetrieveRequestParams, extraHttpRequestParams?: any): Observable<Room>;

    /**
     * 
     * Sets the canonical &#x60;&#x60;pagination_class&#x60;&#x60; and &#x60;&#x60;filter_backends&#x60;&#x60; for every API ViewSet.  Extend this mixin (directly or via &#x60;&#x60;NameSearchMixin&#x60;&#x60;) to avoid repeating these two lines in every class.
     * @endpoint put /location/room/{id}
* @param requestParameters
     */
    locationRoomUpdate(requestParameters: LocationRoomUpdateRequestParams, extraHttpRequestParams?: any): Observable<Room>;

}
