# Generated by Django 6.0.2 on 2026-02-25 07:08

import django.db.models.deletion
from django.db import migrations, models


def _rename_location_table_if_needed(apps, schema_editor):
    """
    On production the table is already named 'datacenter_location'.
    On a freshly-created test database the table is 'location_location'
    (Django's default naming from migration 0001 which lacked db_table).
    Rename it only when the default-named table exists.
    """
    tables = schema_editor.connection.introspection.table_names()
    if 'location_location' in tables:
        schema_editor.execute(
            'ALTER TABLE "location_location" RENAME TO "datacenter_location"'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_room'),
    ]

    operations = [
        # Pin the Location table name to the existing physical table.
        # On production the table is already 'datacenter_location'; for fresh DBs
        # (e.g. test runs) the RunPython below renames it first.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='location',
                    table='datacenter_location',
                ),
            ],
            database_operations=[
                migrations.RunPython(
                    _rename_location_table_if_needed,
                    reverse_code=migrations.RunPython.noop,
                ),
            ],
        ),
        migrations.AlterField(
            model_name='locationcustomfield',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='custom_fields', to='location.location'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='location.location'),
        ),
    ]
