# Generated by Django 6.0.2 on 2026-02-25 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0008_room'),
    ]

    operations = [
        # Pin the Location table name to the existing physical table (no DB op needed).
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterModelTable(
                    name='location',
                    table='datacenter_location',
                ),
            ],
            database_operations=[],
        ),
        migrations.AlterField(
            model_name='locationcustomfield',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='location.location'),
        ),
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='location.location'),
        ),
    ]
