# Generated by Django 6.0.2 on 2026-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_locationcustomfield_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='location',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='location',
            name='manager_mail',
        ),
        migrations.AddField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='manager_mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
