# Generated by Django 6.0.2 on 2026-02-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_remove_location_capacity_remove_location_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='floor_plan_data',
            field=models.JSONField(blank=True, help_text='Interactive floor plan elements (walls, racks, doors) from the Angular editor.', null=True),
        ),
    ]
