# Generated by Django 6.0.2 on 2026-03-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('datacenter', 'Datacenter'), ('warehouse', 'Warehouse'), ('laboratory', 'Laboratory'), ('technical_office', 'Technical Office')], default='datacenter', max_length=20, verbose_name='Room type'),
        ),
    ]
