# Generated by Django 6.0.3 on 2026-03-24 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_move_rack_racktype_from_asset_state_create'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('cable', 'Cavo'), ('fiber', 'Fibra'), ('sfp_switch', 'SFP Switch'), ('sfp_server', 'SFP Server'), ('cable_manager', 'Passacavi'), ('other', 'Altro')], default='other', max_length=20)),
                ('specs', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit', models.CharField(choices=[('pcs', 'pz'), ('m', 'm'), ('box', 'box')], default='pcs', max_length=10)),
                ('min_threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_items', to='location.room')),
            ],
            options={
                'db_table': 'warehouse_item',
                'ordering': ['category', 'name'],
            },
        ),
    ]
