# Generated by Django 6.0.3 on 2026-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0064_populate_standard_states'),
        ('location', '0018_warehouseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseitem',
            name='compatible_models',
            field=models.ManyToManyField(blank=True, related_name='compatible_warehouse_items', to='asset.assetmodel'),
        ),
    ]
