# Generated by Django 6.0.3 on 2026-03-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_warehouseitem_compatible_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='category',
            field=models.CharField(choices=[('cable', 'Cable'), ('fiber', 'Fiber'), ('sfp_switch', 'SFP Switch'), ('sfp_server', 'SFP Server'), ('cable_manager', 'Cable Manager'), ('blanking_panel', 'Blanking Panel'), ('patch_panel', 'Patch Panel'), ('pdu', 'PDU'), ('shelf', 'Shelf'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
