# Generated by Django 6.0.3 on 2026-03-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_warehouseitem_compatible_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseitem',
            name='category',
            field=models.CharField(choices=[('cable', 'Cavo'), ('fiber', 'Fibra'), ('sfp_switch', 'SFP Switch'), ('sfp_server', 'SFP Server'), ('cable_manager', 'Passacavi'), ('blanking_panel', 'Pannello cieco'), ('patch_panel', 'Patch Panel'), ('pdu', 'PDU'), ('shelf', 'Ripiano'), ('other', 'Altro')], default='other', max_length=30),
        ),
    ]
