# Generated by Django 6.0.3 on 2026-03-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_warehouseitem_new_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='racktype',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AlterField(
            model_name='racktype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        # The unique_together constraint already exists in the DB (created by a
        # previous migration or manually). Use SeparateDatabaseAndState to sync
        # Django's migration state without running the duplicate CREATE INDEX.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='rack',
                    unique_together={('name', 'room')},
                ),
            ],
            database_operations=[],
        ),
    ]
