# Generated by Django 6.0.3 on 2026-03-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_assetmodel_id_alter_assetmodelport_id_and_more'),
        ('location', '0021_alter_rack_id_alter_racktype_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationcustomfield',
            name='field_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_custom_fields', to='catalog.customfieldname'),
        ),
        migrations.AlterField(
            model_name='warehouseitem',
            name='compatible_models',
            field=models.ManyToManyField(blank=True, related_name='compatible_warehouse_items', to='catalog.assetmodel'),
        ),
    ]
