# Generated by Django 5.1.6 on 2025-02-09 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0003_rack'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=48)),
            ],
        ),
        migrations.RemoveField(
            model_name='rack',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='occupied_units',
        ),
        migrations.AddField(
            model_name='rack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='locations', to='datacenter.location'),
        ),
    ]
