# Generated by Django 5.1.6 on 2025-02-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacenter', '0004_racktype_remove_rack_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='datacenter.racktype'),
            preserve_default=False,
        ),
    ]
