# Generated by Django 5.1.6 on 2025-02-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0029_racktype_remove_asset_rack_rack'),
        ('datacenter', '0005_rack_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rack',
        ),
        migrations.DeleteModel(
            name='RackType',
        ),
    ]
