# Generated by Django 5.1.6 on 2025-02-08 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(max_length=50)),
                ('purchase_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='assets', to='location.location')),
            ],
        ),
    ]
