# Generated by Django 5.1.6 on 2025-02-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_remove_asset_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='name',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='value',
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='order_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='rack_units',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='sap_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
