# Generated by Django 5.1.6 on 2025-02-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_rename_name_asset_vendor_remove_asset_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='datacenter',
            new_name='location',
        ),
        migrations.AddField(
            model_name='asset',
            name='state',
            field=models.CharField(default='in-use', max_length=50),
        ),
    ]
