# Generated by Django 5.1.6 on 2025-02-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_rename_datacenter_asset_location_asset_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='power_connections',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='asset',
            name='power_cosumption',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
