# Generated by Django 5.1.6 on 2025-02-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_asset_power_connections_asset_power_cosumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='vendor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
