# Generated by Django 5.1.6 on 2025-02-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_vendor_asset_created_at_asset_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
