# Generated by Django 5.1.6 on 2025-02-08 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_asset_state2_alter_asset_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='state',
        ),
    ]
