# Generated by Django 5.1.6 on 2025-02-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0013_remove_asset_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='state2',
            new_name='state',
        ),
    ]
