# Generated by Django 5.1.6 on 2025-02-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0014_rename_state2_asset_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_value', models.CharField(blank=True, max_length=255)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='asset.asset')),
            ],
        ),
    ]
