# Generated by Django 5.1.6 on 2025-02-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0015_assetcustomfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
