# Generated by Django 5.1.6 on 2025-02-08 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0016_asset_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='type',
        ),
    ]
