# Generated by Django 5.1.6 on 2025-02-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0017_rename_asset_type_asset_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('rack_units', models.PositiveIntegerField(default=1)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_type', to='asset.assettype')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_vendor', to='asset.vendor')),
            ],
        ),
    ]
