# Generated by Django 5.1.6 on 2025-02-08 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0018_assetmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='model2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.assetmodel'),
            preserve_default=False,
        ),
    ]
