# Generated by Django 5.1.6 on 2025-02-08 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0019_asset_model2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='model',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rack_units',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='vendor',
        ),
    ]
