# Generated by Django 5.1.6 on 2025-02-08 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0020_remove_asset_model_remove_asset_rack_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='model2',
            new_name='model',
        ),
    ]
