# Generated by Django 5.1.6 on 2025-02-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0021_rename_model2_asset_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='power_connections',
            new_name='power_supplies',
        ),
    ]
