# Generated by Django 5.1.6 on 2025-02-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0022_rename_power_connections_asset_power_supplies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='assetcustomfield',
            name='field_name',
        ),
        migrations.AddField(
            model_name='assetcustomfield',
            name='field_name',
            field=models.ManyToManyField(related_name='field_name', to='asset.field'),
        ),
    ]
