# Generated by Django 5.1.6 on 2025-02-08 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0023_field_remove_assetcustomfield_field_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcustomfield',
            name='field_name',
        ),
        migrations.AddField(
            model_name='assetcustomfield',
            name='field_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='field_name', to='asset.field'),
            preserve_default=False,
        ),
    ]
