# Generated by Django 5.1.6 on 2025-02-08 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0024_remove_assetcustomfield_field_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['hostname'], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.RemoveField(
            model_name='assetstate',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='assetstate',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='assetstate',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='asset',
            name='sap_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='assetstate',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='assetcustomfield',
            unique_together={('asset', 'field_name')},
        ),
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('name', 'vendor', 'type')},
        ),
    ]
