# Generated by Django 5.1.6 on 2025-02-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0025_alter_asset_options_remove_assetstate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='decommissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='support_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
