# Generated by Django 5.1.6 on 2025-02-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0026_asset_decommissioned_date_asset_support_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='front_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='assetmodel',
            name='rear_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='asset',
            name='power_supplies',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
