# Generated by Django 5.1.6 on 2025-02-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0028_asset_rack'),
        ('location', '0005_rack_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='RackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField(default=48)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rack',
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                 related_name='locations', to='location.location')),
                ('model', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='asset.racktype')),
            ],
            options={
                'verbose_name': 'Rack',
                'verbose_name_plural': 'Racks',
                'ordering': ['name'],
                'unique_together': {('name', 'location')},
            },
        ),
    ]
