# Generated by Django 5.1.6 on 2025-02-09 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0029_racktype_remove_asset_rack_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='asset.rack'),
        ),
    ]
