# Generated by Django 5.1.6 on 2025-02-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0031_alter_asset_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='racktype',
            options={'verbose_name': 'Rack Type', 'verbose_name_plural': 'Rack Types'},
        ),
        migrations.AlterModelTable(
            name='assetcustomfield',
            table='asset_custom_field',
        ),
        migrations.AlterModelTable(
            name='assetmodel',
            table='asset_model',
        ),
        migrations.AlterModelTable(
            name='assetstate',
            table='asset_state',
        ),
        migrations.AlterModelTable(
            name='assettype',
            table='asset_type',
        ),
        migrations.AlterModelTable(
            name='field',
            table='custom_field',
        ),
        migrations.AlterModelTable(
            name='rack',
            table='rack',
        ),
        migrations.AlterModelTable(
            name='racktype',
            table='rack_type',
        ),
        migrations.AlterModelTable(
            name='vendor',
            table='vendor',
        ),
    ]
