# Generated by Django 5.1.6 on 2025-02-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0033_rename_field_customfieldname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customfieldname',
            table='custom_field_name',
        ),
    ]
