# Generated by Django 5.1.6 on 2025-02-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0036_remove_asset_rack_rackunit'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rackunit',
            table='rack_unit',
        ),
    ]
