# Generated by Django 5.1.6 on 2025-02-09 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0037_alter_rackunit_device'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rackunit',
            options={'ordering': ['rack', '-unit']},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='rack',
        ),
    ]
