# Generated by Django 5.1.6 on 2025-02-09 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0038_alter_rackunit_options_remove_asset_rack'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rackunit',
            table='rack_unit',
        ),
    ]
