# Generated by Django 5.1.6 on 2025-02-18 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0039_alter_rackunit_options_rename_unit_rackunit_position_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkSwitchAssetModel',
            fields=[
                ('assetmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='asset.assetmodel')),
                ('ports', models.PositiveIntegerField(default=24)),
                ('uplink_ports', models.PositiveIntegerField(default=2)),
            ],
            options={
                'db_table': 'network_switch_asset_model',
            },
            bases=('asset.assetmodel',),
        ),
    ]
