# Generated by Django 6.0.2 on 2026-02-25 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0040_networkswitchassetmodel'),
        ('location', '0010_remove_location_capacity_remove_location_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locations', to='location.location'),
        ),
    ]
