# Generated by Django 6.0.2 on 2026-02-25 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0041_alter_rack_location'),
        ('location', '0010_remove_location_capacity_remove_location_manager_and_more'),
    ]

    operations = [
        # 1. Drop old unique_together (state only — constraint doesn't exist in DB)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='rack',
                    unique_together=set(),
                ),
            ],
            database_operations=[],
        ),
        # 2. Add the new 'room' field
        migrations.AddField(
            model_name='rack',
            name='room',
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racks', to='location.room'),
        ),
        # 3. Remove old 'location' field
        migrations.RemoveField(
            model_name='rack',
            name='location',
        ),
        # 4. Set new unique_together referencing 'room'
        migrations.AlterUniqueTogether(
            name='rack',
            unique_together={('name', 'room')},
        ),
    ]
