# Generated by Django 6.0.2 on 2026-02-28 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0042_alter_rack_unique_together_rack_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.assetmodel'),
        ),
    ]
