# Generated by Django 6.0.2 on 2026-02-28 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0043_protect_asset_model_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_vendor', to='asset.vendor'),
        ),
    ]
