# Generated by Django 6.0.2 on 2026-03-01 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0044_vendor_protect_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='sap_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='serial_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
