# Generated by Django 6.0.3 on 2026-03-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0046_assetmodel_uuid_and_image_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('component_type', models.CharField(choices=[('cable_manager', 'Cable Manager'), ('blanking_panel', 'Blanking Panel'), (
                    'patch_panel', 'Patch Panel'), ('pdu', 'PDU / Power Strip'), ('shelf', 'Shelf'), ('other', 'Other')], default='other', max_length=50)),
                ('rack_units', models.PositiveIntegerField(
                    default=1, help_text='Number of rack units (U) occupied by this component.')),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generic Component',
                'verbose_name_plural': 'Generic Components',
                'db_table': 'generic_component',
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='rackunit',
            name='generic_component',
            field=models.ForeignKey(blank=True, help_text='Generic/consumable component installed in this rack unit (mutually exclusive with device).',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_in_rack_units', to='asset.genericcomponent'),
        ),
    ]
