# Generated by Django 6.0.3 on 2026-03-04 19:23

import asset.utils.upload_paths
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0047_generic_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcomponent',
            name='front_image',
            field=models.ImageField(blank=True, help_text='Front-face image of the component.', null=True, upload_to=asset.utils.upload_paths.generic_component_front_upload),
        ),
        migrations.AddField(
            model_name='genericcomponent',
            name='rear_image',
            field=models.ImageField(blank=True, help_text='Rear-face image of the component.', null=True, upload_to=asset.utils.upload_paths.generic_component_rear_upload),
        ),
        migrations.AddField(
            model_name='genericcomponent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
