# Generated by Django 6.0.3 on 2026-03-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0048_generic_component_images'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['hostname'], name='asset_hostname_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['state', 'model'], name='asset_state_model_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['-updated_at'], name='asset_updated_at_idx'),
        ),
    ]
