# Generated by Django 6.0.3 on 2026-03-08 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0049_add_asset_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetModelPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('port_type', models.CharField(choices=[('RJ45', 'RJ45 (1GbE)'), ('SFP', 'SFP (1G)'), ('SFP+', 'SFP+ (10G)'), ('SFP28', 'SFP28 (25G)'), ('QSFP+', 'QSFP+ (40G)'), ('QSFP28', 'QSFP28 (100G)'), ('QSFP-DD', 'QSFP-DD (400G)'), ('LC', 'LC Fiber'), ('SC', 'SC Fiber'), ('FC', 'Fibre Channel'), ('USB-A', 'USB-A'), ('USB-C', 'USB-C'), ('SERIAL', 'Serial Console'), ('MGMT', 'Management'), ('HDMI', 'HDMI'), ('VGA', 'VGA'), ('OTHER', 'Other')], default='RJ45', max_length=16)),
                ('side', models.CharField(choices=[('front', 'Front'), ('rear', 'Rear')], default='rear', max_length=5)),
                ('pos_x', models.FloatField(blank=True, null=True)),
                ('pos_y', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_ports', to='asset.assetmodel')),
            ],
            options={
                'db_table': 'asset_model_port',
                'ordering': ['side', 'name'],
            },
        ),
    ]
