# Generated by Django 6.0.3 on 2026-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0051_assetmodel_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='power_consumption_watt',
            field=models.PositiveIntegerField(default=0, help_text='Consumo energetico globale (W)'),
        ),
    ]
