# Generated by Django 6.0.3 on 2026-03-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0052_assetmodel_power_consumption_watt'),
    ]

    operations = [
        migrations.AddField(
            model_name='racktype',
            name='depth',
            field=models.PositiveIntegerField(default=1000, help_text='Depth in mm'),
        ),
    ]
