# Generated by Django 6.0.3 on 2026-03-21 13:44

from django.db import migrations


def copy_height_to_depth(apps, schema_editor):
    RackType = apps.get_model('asset', 'RackType')
    for rack in RackType.objects.all():
        # Copy the value from the old 'height' field to the new 'depth' field.
        # Note: 'height' was storing depth values incorrectly.
        # If value is small (< 300), assume it was cm and convert to mm.
        if rack.height < 300:
            rack.depth = rack.height
        else:
            rack.depth = rack.height
        rack.save()


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0053_racktype_depth'),
    ]

    operations = [
        migrations.RunPython(copy_height_to_depth),
        migrations.RemoveField(
            model_name='racktype',
            name='height',
        ),
    ]
