# Generated by Django 6.0.3 on 2026-03-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0054_remove_racktype_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racktype',
            name='depth',
            field=models.PositiveIntegerField(),
        ),
    ]
