# Generated by Django 6.0.3 on 2026-03-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0055_alter_racktype_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='racktype',
            name='height',
            field=models.PositiveIntegerField(blank=True, help_text='Height in cm', null=True),
        ),
    ]
