# Generated by Django 6.0.3 on 2026-03-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0056_racktype_height'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rackunit',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('device__isnull', False), ('generic_component__isnull', True)), models.Q(('device__isnull', True), ('generic_component__isnull', False)), models.Q(('device__isnull', True), ('generic_component__isnull', True)), _connector='OR'), name='rack_unit_device_xor_generic_component'),
        ),
    ]
