# Generated by Django 6.0.3 on 2026-03-21 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0057_rack_unit_device_xor_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='asset.assetstate'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='asset.racktype'),
        ),
        migrations.AlterField(
            model_name='rackunit',
            name='device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='asset.asset'),
        ),
    ]
