# Generated by Django 6.0.3 on 2026-03-24 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0064_populate_standard_states'),
        ('location', '0020_warehouseitem_new_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericcomponent',
            name='warehouse_item',
            field=models.ForeignKey(blank=True, help_text='Warehouse item used when the component is installed in a rack.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_definitions', to='location.warehouseitem'),
        ),
    ]
