# Generated by Django 6.0.3 on 2026-03-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0066_asset_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetrequest',
            name='clarification_notes',
            field=models.TextField(blank=True, help_text='Richiesta di chiarimento inviata al richiedente', verbose_name='Note di chiarimento'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Motivazione o dettagli della richiesta', verbose_name='Note'),
        ),
    ]
