# Generated by Django 6.0.3 on 2026-03-28 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0068_extract_catalog'),
        ('location', '0022_alter_locationcustomfield_field_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'ordering': [
                '-created_at'], 'verbose_name': 'Asset request', 'verbose_name_plural': 'Asset requests'},
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='asset_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigned to'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='clarification_notes',
            field=models.TextField(
                blank=True, help_text='Clarification request sent to the requester', verbose_name='Clarification notes'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='asset_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='asset_requests_executed', to=settings.AUTH_USER_MODEL, verbose_name='Executed by'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='from_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='asset_requests_from', to='location.room', verbose_name='Source location'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='from_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                    related_name='requests_from', to='asset.assetstate', verbose_name='Source asset state'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='notes',
            field=models.TextField(
                blank=True, help_text='Request rationale or details', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='planned_date',
            field=models.DateField(blank=True, null=True,
                                   verbose_name='Planned date'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='rejection_notes',
            field=models.TextField(
                blank=True, verbose_name='Rejection reason'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='request_type',
            field=models.CharField(choices=[('registrazione', 'Registration'), ('spostamento', 'Relocation'), (
                'manutenzione', 'Maintenance'), ('dismissione', 'Decommissioning')], max_length=20, verbose_name='Request type'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('inserita', 'Submitted'), ('pianificata', 'Planned'), ('evasa', 'Executed'), ('rifiutata', 'Rejected'), (
                'in_chiarimento', 'Needs Clarification')], db_index=True, default='inserita', max_length=20, verbose_name='Request status'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='to_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='asset_requests_to', to='location.room', verbose_name='Target location'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='to_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='requests_to', to='asset.assetstate', verbose_name='Target asset state'),
        ),
        migrations.AlterField(
            model_name='assetstate',
            name='code',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('in_preparation', 'In Preparation'), ('in_maintenance', 'In Maintenance'), (
                'in_production', 'In Production'), ('decommissioned', 'Decommissioned')], default=None, max_length=30, null=True, unique=True),
        ),
    ]
