# Generated by Django 6.0.3 on 2026-03-29 03:33

from django.db import migrations, models


def migrate_assetrequest_enums_to_english(apps, schema_editor):
    AssetRequest = apps.get_model('asset', 'AssetRequest')

    type_map = {
        'registrazione': 'registration',
        'spostamento': 'relocation',
        'manutenzione': 'maintenance',
        'dismissione': 'decommissioning',
    }
    status_map = {
        'inserita': 'submitted',
        'pianificata': 'planned',
        'evasa': 'executed',
        'rifiutata': 'rejected',
        'in_chiarimento': 'needs_clarification',
    }

    for old_value, new_value in type_map.items():
        AssetRequest.objects.filter(request_type=old_value).update(request_type=new_value)
    for old_value, new_value in status_map.items():
        AssetRequest.objects.filter(status=old_value).update(status=new_value)


def reverse_migrate_assetrequest_enums_to_italian(apps, schema_editor):
    AssetRequest = apps.get_model('asset', 'AssetRequest')

    type_map = {
        'registration': 'registrazione',
        'relocation': 'spostamento',
        'maintenance': 'manutenzione',
        'decommissioning': 'dismissione',
    }
    status_map = {
        'submitted': 'inserita',
        'planned': 'pianificata',
        'executed': 'evasa',
        'rejected': 'rifiutata',
        'needs_clarification': 'in_chiarimento',
    }

    for old_value, new_value in type_map.items():
        AssetRequest.objects.filter(request_type=old_value).update(request_type=new_value)
    for old_value, new_value in status_map.items():
        AssetRequest.objects.filter(status=old_value).update(status=new_value)


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0069_alter_assetrequest_options_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_assetrequest_enums_to_english,
            reverse_migrate_assetrequest_enums_to_italian,
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='request_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('relocation', 'Relocation'), ('maintenance', 'Maintenance'), ('decommissioning', 'Decommissioning')], max_length=20, verbose_name='Request type'),
        ),
        migrations.AlterField(
            model_name='assetrequest',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('planned', 'Planned'), ('executed', 'Executed'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], db_index=True, default='submitted', max_length=20, verbose_name='Request status'),
        ),
    ]
