# Generated by Django 6.0.3 on 2026-03-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0071_migrate_assetrequest_values_to_english'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetstate',
            name='code',
            field=models.CharField(blank=True, choices=[('in_stock', 'In Stock'), ('in_preparation', 'In Preparation'), ('in_maintenance', 'In Maintenance'), ('in_production', 'In Production'), ('decommissioned', 'Decommissioned')], default=None, max_length=30, null=True, unique=True),
        ),
    ]
