# Generated by Django 6.0.4 on 2026-04-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0073_migrate_assetstate_codes_to_english'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetNetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name, e.g. "NIC 1", "eth0", "ens3f0"', max_length=64, verbose_name='Name')),
                ('media_type', models.CharField(choices=[('copper', 'Copper (RJ45 / 10GBASE-T)'), ('fiber', 'Fiber (SFP / DAC)')], default='copper', max_length=10, verbose_name='Media type')),
                ('port_count', models.PositiveSmallIntegerField(choices=[(1, 'Single port (1×)'), (2, 'Dual port (2×)'), (4, 'Quad port (4×)')], default=1, verbose_name='Port count')),
                ('speed', models.CharField(choices=[('100M', '100 Mbps'), ('1G', '1 GbE'), ('10G', '10 GbE'), ('25G', '25 GbE'), ('40G', '40 GbE'), ('100G', '100 GbE'), ('200G', '200 GbE'), ('400G', '400 GbE')], default='1G', max_length=8, verbose_name='Speed')),
                ('slot', models.CharField(blank=True, default='', help_text='Physical slot identifier, e.g. "PCIe 3", "Mezz 1"', max_length=32, verbose_name='Slot')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Notes')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_interfaces', to='asset.asset', verbose_name='Asset')),
            ],
            options={
                'verbose_name': 'Network interface',
                'verbose_name_plural': 'Network interfaces',
                'db_table': 'asset_network_interface',
                'ordering': ['name'],
            },
        ),
    ]
