# Generated by Django 6.0.4 on 2026-04-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0074_asset_network_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Horizontal center position as percentage 0–100', null=True, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Vertical center position as percentage 0–100', null=True, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='side',
            field=models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear')], default='rear', help_text='Panel side where the NIC is visible (front or rear)', max_length=5, verbose_name='Side'),
        ),
    ]
