# Generated by Django 6.0.4 on 2026-04-14 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0075_nic_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='height',
            field=models.FloatField(blank=True, help_text='Rectangle height as percentage 0–100', null=True, verbose_name='Height'),
        ),
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='width',
            field=models.FloatField(blank=True, help_text='Rectangle width as percentage 0–100', null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='assetnetworkinterface',
            name='pos_x',
            field=models.FloatField(blank=True, help_text='Top-left X position as percentage 0–100', null=True, verbose_name='Position X'),
        ),
        migrations.AlterField(
            model_name='assetnetworkinterface',
            name='pos_y',
            field=models.FloatField(blank=True, help_text='Top-left Y position as percentage 0–100', null=True, verbose_name='Position Y'),
        ),
    ]
