# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0076_nic_rect_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='form_factor',
            field=models.CharField(
                choices=[('full', 'Full profile'), ('low', 'Low profile')],
                default='full',
                help_text='PCIe bracket height: full profile or low profile',
                max_length=4,
                verbose_name='Form factor',
            ),
        ),
    ]
