# Generated by Django 6.0.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0077_nic_form_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetnetworkinterface',
            name='orientation',
            field=models.CharField(
                choices=[('vertical', 'Vertical'),
                         ('horizontal', 'Horizontal')],
                default='vertical',
                help_text='Physical installation orientation: vertical (standard) or horizontal',
                max_length=10,
                verbose_name='Orientation',
            ),
        ),
    ]
