/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortTypeEnum } from './portTypeEnum';
import { SideEnum } from './sideEnum';


export interface AssetModelPort { 
    readonly id: number;
    asset_model: number;
    name: string;
    port_type?: PortTypeEnum;
    side?: SideEnum;
    pos_x?: number | null;
    pos_y?: number | null;
    notes?: string;
}
export namespace AssetModelPort {
}


