/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Body to resubmit a request after clarification (IN_CHIARIMENTO → INSERITA).
 */
export interface AssetRequestResubmit { 
    notes?: string;
}

