/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetAssetModelImportCreateRequest { 
    name: string;
    vendor: string;
    type: string;
    rack_units?: number;
    note?: string;
    front_image?: string;
    rear_image?: string;
}

