/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetModelType } from './assetModelType';
import { AssetModel } from './assetModel';


export interface Asset { 
    readonly url?: string;
    readonly id?: string;
    model: AssetModel;
    state: AssetModelType;
    hostname?: string;
    serial_number?: string;
    sap_id?: string;
    order_id?: string;
    purchase_date?: string | null;
    decommissioned_date?: string | null;
    warranty_expiration?: string | null;
    support_expiration?: string | null;
    power_supplies?: number;
    power_cosumption_watt?: number;
    note?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}

