/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssetAssetAssetModelImportCreateRequest { 
    name: string;
    /**
     * Vendor name (created if missing)
     */
    vendor: string;
    /**
     * AssetType name (created if missing)
     */
    type: string;
    rack_units?: number;
    note?: string;
    /**
     * Data URL (base64) — optional
     */
    front_image?: string;
    /**
     * Data URL (base64) — optional
     */
    rear_image?: string;
}

