/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetModel } from './assetModel';
import { AssetState } from './assetState';


/**
 * Serializer for the Asset model.  This serializer uses HyperlinkedModelSerializer to serialize the Asset model with the following fields: - id: Read-only field representing the unique identifier of the asset. - model: Nested serializer for the asset model. - state: Nested serializer for the asset state.  Meta:     model: The model class that is being serialized.     fields: Specifies that all fields in the model should be included in the serialization.
 */
export interface Asset { 
    readonly url: string;
    readonly id: number;
    model: AssetModel;
    state: AssetState;
    hostname?: string;
    serial_number?: string;
    sap_id?: string;
    order_id?: string;
    purchase_date?: string | null;
    decommissioned_date?: string | null;
    warranty_expiration?: string | null;
    support_expiration?: string | null;
    power_supplies?: number;
    power_cosumption_watt?: number;
    note?: string;
    readonly created_at: string;
    readonly updated_at: string;
}

