/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CodeEnum } from './codeEnum';
import { BlankEnum } from './blankEnum';


/**
 * @type AssetStateCode
 * @export
 */
export type AssetStateCode = BlankEnum | CodeEnum;

