/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for the AssetType model.  This serializer converts AssetType model instances into JSON format and vice versa. It includes the following fields:     - name: The name of the asset type.  Attributes:     Meta (class): Meta options for the serializer.         model (AssetType): The model that is being serialized.         fields (list): The list of fields to be included in the serialization.
 */
export interface AssetType { 
    readonly id: number;
    name: string;
}

