/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatusEnum } from './statusEnum';
import { RequestTypeEnum } from './requestTypeEnum';


/**
 * Read serializer for an asset request (list and detail).
 */
export interface AssetRequest { 
    readonly id: number;
    asset: number;
    readonly asset_hostname: string;
    request_type: RequestTypeEnum;
    readonly status: StatusEnum;
    from_state?: number | null;
    readonly from_state_name: string;
    to_state: number;
    readonly to_state_name: string;
    from_room?: number | null;
    readonly from_room_name: string;
    to_room?: number | null;
    readonly to_room_name: string;
    /**
     * Request rationale or details
     */
    notes?: string;
    /**
     * Clarification request sent to the requester
     */
    readonly clarification_notes: string;
    readonly rejection_notes: string;
    planned_date?: string | null;
    readonly created_by: number;
    readonly created_by_username: string;
    assigned_to?: number | null;
    readonly assigned_to_username: string;
    readonly executed_by: number | null;
    readonly executed_by_username: string;
    readonly created_at: string;
    readonly updated_at: string;
}
export namespace AssetRequest {
}


