/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestTypeEnum } from './requestTypeEnum';

/**
 * Serializer for creating a new request.
 */
export interface AssetRequestCreate {
  asset: number;
  request_type: RequestTypeEnum;
  to_state: number;
  to_room?: number | null;
  /**
   * Request rationale or details
   */
  notes?: string;
  planned_date?: string | null;
  assigned_to?: number | null;
}
export namespace AssetRequestCreate {}
