/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AuthMeRetrieve200ResponseRole { 
    id?: number;
    name?: string;
    can_create?: boolean;
    can_edit?: boolean;
    can_delete?: boolean;
    can_import_export?: boolean;
    can_access_assets?: boolean;
    can_access_catalog?: boolean;
    can_manage_users?: boolean;
}

