/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthMeRetrieve200ResponseRole } from './authMeRetrieve200ResponseRole';

export interface AuthMeRetrieve200Response {
  id?: number;
  username?: string;
  email?: string;
  role?: AuthMeRetrieve200ResponseRole;
}
