/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `cable` - Cavo * `fiber` - Fibra * `sfp_switch` - SFP Switch * `sfp_server` - SFP Server * `cable_manager` - Passacavi * `blanking_panel` - Pannello cieco * `patch_panel` - Patch Panel * `pdu` - PDU * `shelf` - Ripiano * `other` - Altro
 */
export const CategoryEnum = {
    Cable: 'cable',
    Fiber: 'fiber',
    SfpSwitch: 'sfp_switch',
    SfpServer: 'sfp_server',
    CableManager: 'cable_manager',
    BlankingPanel: 'blanking_panel',
    PatchPanel: 'patch_panel',
    Pdu: 'pdu',
    Shelf: 'shelf',
    Other: 'other'
} as const;
export type CategoryEnum = typeof CategoryEnum[keyof typeof CategoryEnum];

