/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `in_stock` - In Stock * `in_preparazione` - In Preparazione * `in_manutenzione` - In Manutenzione * `in_produzione` - In Produzione * `dismesso` - Dismesso
 */
export const CodeEnum = {
    InStock: 'in_stock',
    InPreparazione: 'in_preparazione',
    InManutenzione: 'in_manutenzione',
    InProduzione: 'in_produzione',
    Dismesso: 'dismesso'
} as const;
export type CodeEnum = typeof CodeEnum[keyof typeof CodeEnum];

