/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `cable_manager` - Cable Manager * `blanking_panel` - Blanking Panel * `patch_panel` - Patch Panel * `pdu` - PDU / Power Strip * `shelf` - Shelf * `other` - Other
 */
export const ComponentTypeEnum = {
    CableManager: 'cable_manager',
    BlankingPanel: 'blanking_panel',
    PatchPanel: 'patch_panel',
    Pdu: 'pdu',
    Shelf: 'shelf',
    Other: 'other'
} as const;
export type ComponentTypeEnum = typeof ComponentTypeEnum[keyof typeof ComponentTypeEnum];

