/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Minimal read-only representation of an AssetModel for compatibility.
 */
export interface CompatibleModelBrief { 
    readonly id: number;
    readonly name: string;
    readonly vendor_name: string;
}

