/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `full` - Full profile * `low` - Low profile
 */
export const FormFactorEnum = {
    Full: 'full',
    Low: 'low'
} as const;
export type FormFactorEnum = typeof FormFactorEnum[keyof typeof FormFactorEnum];

