/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComponentTypeEnum } from './componentTypeEnum';


/**
 * Serializer for GenericComponent model.  Exposes all fields of a generic/consumable rack-mounted component.
 */
export interface GenericComponent { 
    readonly id: number;
    name: string;
    component_type?: ComponentTypeEnum;
    readonly component_type_display: string;
    /**
     * Number of rack units (U) occupied by this component.
     */
    rack_units?: number;
    note?: string;
    readonly created_at: string;
    readonly updated_at: string;
}
export namespace GenericComponent {
}


