/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `auto` - Auto * `metric` - Metric * `imperial` - Imperial
 */
export const MeasurementSystemEnum = {
    Auto: 'auto',
    Metric: 'metric',
    Imperial: 'imperial'
} as const;
export type MeasurementSystemEnum = typeof MeasurementSystemEnum[keyof typeof MeasurementSystemEnum];

