/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `admin` - Admin * `editor` - Editor * `viewer` - Viewer
 */
export const NameEnum = {
    Admin: 'admin',
    Editor: 'editor',
    Viewer: 'viewer'
} as const;
export type NameEnum = typeof NameEnum[keyof typeof NameEnum];

