/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Asset } from './asset';


export interface PaginatedAssetList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<Asset>;
}

