/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Room } from './room';

export interface PaginatedRoomList {
  count: number;
  next?: string;
  previous?: string;
  results: Array<Room>;
}
