/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserList } from './userList';


export interface PaginatedUserListList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<UserList>;
}

