/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RackUnit } from './rackUnit';


export interface PaginatedRackUnitList { 
    count: number;
    next?: string;
    previous?: string;
    results: Array<RackUnit>;
}

