/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryEnum } from './categoryEnum';
import { UnitEnum } from './unitEnum';
import { CompatibleModelBrief } from './compatibleModelBrief';


export interface PatchedWarehouseItem { 
    readonly id?: number;
    name?: string;
    category?: CategoryEnum;
    readonly category_display?: string;
    specs?: string;
    quantity?: string;
    unit?: UnitEnum;
    readonly unit_display?: string;
    min_threshold?: string | null;
    readonly below_threshold?: boolean;
    warehouse?: number;
    compatible_models?: Array<CompatibleModelBrief>;
    compatible_model_ids?: Array<number>;
    notes?: string;
    readonly created_at?: string;
    readonly updated_at?: string;
}
export namespace PatchedWarehouseItem {
}


