/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MeasurementSystemEnum } from './measurementSystemEnum';


export interface PatchedUserPreferences { 
    measurement_system?: MeasurementSystemEnum;
}
export namespace PatchedUserPreferences {
}


