/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RackType } from './rackType';


/**
 * RackSerializer is a serializer for the Rack model.  Attributes:     model (RackTypeSerializer): Serializer for the RackType model (read).     model_id (PrimaryKeyRelatedField): Write-only FK to RackType for creation/update.     room (StringRelatedField): Read-only field representing the room of the rack.     room_id (PrimaryKeyRelatedField): Write-only FK to Room for creation/update.     location_name (StringRelatedField): Read-only field representing the location name.     used_units (IntegerField): Annotated count of occupied rack units.     total_power_watt (IntegerField): Annotated sum of device power consumption.
 */
export interface PatchedRack { 
    readonly id?: number;
    name?: string;
    readonly model?: RackType;
    model_id?: number;
    readonly room?: string;
    room_id?: number | null;
    readonly location_name?: string;
    readonly used_units?: number;
    readonly total_power_watt?: number;
}

