/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssetType } from './assetType';
import { AssetModelPort } from './assetModelPort';
import { Vendor } from './vendor';


export interface PatchedAssetModel { 
    readonly id?: number;
    readonly uuid?: string;
    name?: string;
    readonly vendor?: Vendor;
    vendor_id?: number;
    readonly type?: AssetType;
    type_id?: number;
    rack_units?: number;
    width_mm?: number | null;
    height_mm?: number | null;
    depth_mm?: number | null;
    weight_kg?: string | null;
    power_consumption_watt?: number;
    front_image?: string | null;
    front_image_transform?: string;
    rear_image?: string | null;
    rear_image_transform?: string;
    note?: string;
    readonly ports?: Array<AssetModelPort>;
}

