/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortCorrectionResponse { 
    saved: boolean;
    predicted_type: string;
    actual_type: string;
    training_triggered: boolean;
    corrections_since_last_train: number;
    total_corrections: number;
}

