/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortClickAnalyzeResponse { 
    is_port: boolean;
    port_type: string | null;
    name: string | null;
    confidence: number;
}

