/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RackUnit { 
    readonly id?: number;
    readonly rack_id?: string;
    readonly rack_name?: string;
    readonly location_id?: string;
    readonly location_name?: string;
    readonly device_id?: string;
    readonly device_hostname?: string;
    readonly device_model?: string;
    readonly device_vendor?: string;
    readonly device_type?: string;
    readonly rack_installation_front?: boolean;
}

