/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RackModel } from './rackModel';


export interface Rack { 
    name: string;
    model: RackModel;
    readonly location?: string;
    readonly location_short?: string;
}

