/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Serializer for the RackType model.  Fields: id, model, width, height, capacity.
 */
export interface RackType { 
    readonly id: number;
    model: string;
    width: number;
    height: number;
    /**
     * Depth in mm
     */
    depth?: number;
    capacity: number;
}

