/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RackType } from './rackType';


/**
 * RackSerializer is a serializer for the Rack model, utilizing HyperlinkedModelSerializer.  Attributes:     model (RackTypeSerializer): Serializer for the RackType model (read).     model_id (PrimaryKeyRelatedField): Write-only FK to RackType for creation/update.     room (serializers.StringRelatedField): Read-only field representing the room of the rack.     room_id (PrimaryKeyRelatedField): Write-only FK to Room for creation/update.     location_name (serializers.StringRelatedField): Read-only field representing the location name.  Meta:     model (Rack): The model that is being serialized.     fields (list): List of fields to be included in the serialized output.
 */
export interface Rack { 
    readonly id: number;
    name: string;
    readonly model: RackType;
    model_id: number;
    readonly room: string;
    room_id?: number | null;
    readonly location_name: string;
    readonly used_units: number;
    readonly total_power_watt: number;
}

