/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `registration` - Registration * `relocation` - Relocation * `maintenance` - Maintenance * `decommissioning` - Decommissioning
 */
export const RequestTypeEnum = {
    Registration: 'registration',
    Relocation: 'relocation',
    Maintenance: 'maintenance',
    Decommissioning: 'decommissioning'
} as const;
export type RequestTypeEnum = typeof RequestTypeEnum[keyof typeof RequestTypeEnum];

