/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NameEnum } from './nameEnum';

export interface Role {
  readonly id: number;
  readonly name: NameEnum;
  readonly can_view_assets: boolean;
  readonly can_create_assets: boolean;
  readonly can_edit_assets: boolean;
  readonly can_delete_assets: boolean;
  readonly can_import_assets: boolean;
  readonly can_export_assets: boolean;
  readonly can_clone_assets: boolean;
  readonly can_view_catalog: boolean;
  readonly can_create_catalog: boolean;
  readonly can_edit_catalog: boolean;
  readonly can_delete_catalog: boolean;
  readonly can_import_catalog: boolean;
  readonly can_view_infrastructure: boolean;
  readonly can_create_racks: boolean;
  readonly can_edit_racks: boolean;
  readonly can_delete_racks: boolean;
  readonly can_edit_map: boolean;
  readonly can_manage_users: boolean;
}
export namespace Role {}
