/**
 * Datacenter API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * RoomSerializer is a HyperlinkedModelSerializer for the Room model.  Fields:     id (IntegerField): Read-only field for the unique identifier of the room.     url (HyperlinkedIdentityField): Read-only field for the URL of the room detail view.     floor_plan_url (SerializerMethodField): Absolute URL of the floor plan image, if present.  Meta:     model (Room): The model that is being serialized.     fields (str): Specifies that all fields of the model should be included in the serialization.
 */
export interface Room {
  readonly url: string;
  readonly id: number;
  readonly floor_plan_url: string | null;
  floor_plan_data?: Array<{ [key: string]: any }> | null;
  name: string;
  floor?: number | null;
  description?: string | null;
  capacity?: number;
  manager?: string;
  manager_mail?: string | null;
  floor_plan?: string | null;
  readonly created_at: string;
  readonly updated_at: string;
  location: string;
}
