/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `front` - Front * `rear` - Rear
 */
export const SideEnum = {
    Front: 'front',
    Rear: 'rear'
} as const;
export type SideEnum = typeof SideEnum[keyof typeof SideEnum];

