/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `submitted` - Submitted * `planned` - Planned * `executed` - Executed * `rejected` - Rejected * `needs_clarification` - Needs Clarification
 */
export const StatusEnum = {
    Submitted: 'submitted',
    Planned: 'planned',
    Executed: 'executed',
    Rejected: 'rejected',
    NeedsClarification: 'needs_clarification'
} as const;
export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];

