/**
 * Datacenter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `pcs` - pz * `m` - m * `box` - box
 */
export const UnitEnum = {
    Pcs: 'pcs',
    M: 'm',
    Box: 'box'
} as const;
export type UnitEnum = typeof UnitEnum[keyof typeof UnitEnum];

