"""
Django settings for datacenter project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from import_export.formats.base_formats import CSV, XLSX
from datetime import timedelta
from pathlib import Path
from django.utils.translation import gettext_lazy as _
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'reversion',
    "corsheaders",
    'import_export',
    'accounts',
    'location',
    'catalog',
    'asset',
    'drf_spectacular',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'datacenter-app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'datacenter-app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # },
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': config('DB_NAME', default='rack_mount'),
        'USER': config('DB_USER', default='rack'),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='127.0.0.1'),
        'PORT': config('DB_PORT', default='3306'),
        # Keep DB connections open for a short period to reduce reconnect overhead.
        'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=60, cast=int),
    }
}

# Use an in-memory SQLite DB for test runs so `./manage.py test` works on a
# fresh checkout without needing a pre-built test database.  MIGRATE=False
# builds tables from the current model state instead of replaying migrations,
# which avoids failures in SeparateDatabaseAndState migrations that assume
# production columns already exist.
RUNNING_TESTS = 'test' in sys.argv
if RUNNING_TESTS:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
        'TEST': {
            'NAME': ':memory:',
            'MIGRATE': False,
        },
    }

# ── Redis Caching (Django 6.0 optimization) ───────────────────────────────────
# Caches frequently-accessed data (auth/me, roles, catalog) to reduce database hits.
# Use Redis only when explicitly enabled via USE_REDIS_CACHE.
REDIS_HOST = config('REDIS_HOST', default='127.0.0.1')
REDIS_PORT = config('REDIS_PORT', default=6379, cast=int)
REDIS_DB = config('REDIS_DB', default=1, cast=int)
REDIS_PASSWORD = config('REDIS_PASSWORD', default='')
USE_REDIS_CACHE = config('USE_REDIS_CACHE', default=False, cast=bool)

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'datacenter-local-cache',
        'TIMEOUT': 300,
    }
}

if USE_REDIS_CACHE:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}' if REDIS_PASSWORD else f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}',
            'OPTIONS': {
                'CONNECTION_POOL_KWARGS': {
                    'max_connections': 50,
                    'decode_responses': False,
                    'retry_on_timeout': True,
                },
                'socket_connect_timeout': 5,
                'socket_timeout': 5,
                'socket_keepalive': True,
            },
            'KEY_PREFIX': 'datacenter',
            'TIMEOUT': 300,  # 5-minute default cache TTL
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

LANGUAGES = [
    ('en', _('English')),
    ('it', _('Italian')),
    ('de', _('German')),
    ('fr', _('French')),
    ('zh-hans', _('Chinese (Simplified)')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ACCESS_LIST = config('ACCESS_LIST', default='127.0.0.1', cast=Csv())

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/hour',
        'user': '1000/hour',
        # ─── Auth-specific scopes (login / token endpoints) ───────────────────
        # Username+password login attempts (brute-force protection)
        'login_anon': '20/hour',
        # Token refresh calls (automatic every 15 min + F5)
        'token_refresh': '300/hour',
        'media_file': '600/hour',          # Image/file serving requests
        # ─── YOLO-specific throttle scopes ────────────────────────────────────
        'port_training': '10/hour',              # Annotation submissions
        'port_correction': '30/hour',            # Correction submissions
        'port_analysis': '100/hour',             # Full-image analyses
        'port_click_analysis': '200/hour',       # Click-based analyses
        'model_training_status': '1000/hour',    # Status polling
        'anon_port_training': '0/hour',          # Block anonymous
        'anon_port_correction': '0/hour',        # Block anonymous
        # ─── Import / Export scopes ────────────────────────────────────────────
        'asset_import': '10/hour',               # CSV import (bulk DB writes)
        # XLSX export (full-table reads)
        'asset_export': '30/hour',
        'catalog_import': '10/hour',             # JSON catalog import
        # Catalog export (image encoding)
        'catalog_export': '30/hour',
    },
}

# Disable API throttling in local development to avoid 429 during intensive
# annotation/correction workflows. Keep rate limiting enabled in production.
if DEBUG:
    REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = []
    REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
        scope: ('100000/hour' if rate != '0/hour' else rate)
        for scope, rate in REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'].items()
    }

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,  # ✓ Revoke old refresh tokens after rotation
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Datacenter API',
    'DESCRIPTION': 'API app Datacenter',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_PATCH': True,
    'SERVE_URLCONF': 'datacenter-app.urls',
    'PUBLIC': True,
    'OAS_VERSION': '3.1.1',
    'SERVE_PERMISSIONS': ['datacenter-app.permissions.AccessListPermission'],
}

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://127.0.0.1:4200,http://localhost:4200,http://127.0.0.1:8080,http://localhost:8080',
    cast=Csv(),
)

# Never allow all origins — always use explicit CORS_ALLOWED_ORIGINS whitelist
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'accept-language',
    'access-control-allow-origin',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'csrftoken',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://127.0.0.1:4200,http://localhost:4200,http://127.0.0.1:8080,http://localhost:8080',
    cast=Csv(),
)

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

USE_X_FORWARDED_HOST = True
SCRIPT_NAME = "/api"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Media Storage (separated public/private) ───────────────────────────────────
MEDIA_ROOT = 'files'
MEDIA_URL = '/files/'

# Public media directory: images, logos, static assets (no permission checks)
PUBLIC_MEDIA_SUBDIR = 'public'

# Private media directory: training data, sensitive images (permission checks required)
PRIVATE_MEDIA_SUBDIR = 'private'

# Signed URL expiry (3 days by default)
SIGNED_URL_EXPIRY_SECONDS = 3 * 24 * 60 * 60  # 3 days

# Signed URL secret key.
# In production this must be explicitly configured via environment.
SIGNED_URL_SECRET = config('SIGNED_URL_SECRET', default='').strip()
if not SIGNED_URL_SECRET:
    if DEBUG:
        # Dev-only fallback: use SECRET_KEY only when no explicit value is set.
        SIGNED_URL_SECRET = SECRET_KEY
    else:
        raise RuntimeError('SIGNED_URL_SECRET must be set when DEBUG=False')


X_FRAME_OPTIONS = 'DENY'

# ── Upload size limits ────────────────────────────────────────────────────────
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024   # 10 MB

# ── HTTPS / Security headers (enforced only outside DEBUG) ───────────────────
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True

EXPORT_FORMATS = [CSV, XLSX]

# ── Celery ────────────────────────────────────────────────────────────────────
# Use Redis as broker (same instance as caching when enabled).
# Worker startup: celery -A datacenter-app worker -l info
CELERY_BROKER_URL = config(
    'CELERY_BROKER_URL',
    default=f'redis://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/2' if REDIS_PASSWORD
    else f'redis://{REDIS_HOST}:{REDIS_PORT}/2',
)
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'
# Tasks are fire-and-forget; state is tracked in training_state.json
CELERY_TASK_IGNORE_RESULT = True
# Prevent tasks accumulating if the worker is down for a long time
CELERY_TASK_SOFT_TIME_LIMIT = 3600   # 1 hour soft limit (signals SIGTERM)
CELERY_TASK_TIME_LIMIT = 3900        # 1 h 5 min hard limit (signals SIGKILL)

# AUTH_USER_MODEL = "accounts.CustomUser"

# ── Logging ───────────────────────────────────────────────────────────────────
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(LOGS_DIR / 'django.log'),
            'maxBytes': 10 * 1024 * 1024,  # 10 MB per file
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'asset': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'catalog': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'location': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'files': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}
